WPScan February CVEs
CVEProject/cvelist pull request #1239
Opened 2021-04-02 13:18 UTC by ethicalhack3r

CVE-2021-24150 to CVE-2021-24168

First time using an automated script to generate the JSON.

2021-04-02 13:20 UTC, cve-team requested changes
Auto validation errors:

2021-04-02 13:20 UTC, cve-team commented on 2021/24xxx/CVE-2021-24154.json
>  {
[] is too short

2021-04-02 13:20 UTC, cve-team commented on 2021/24xxx/CVE-2021-24163.json
>  {
[] is too short

2021-04-02 13:20 UTC, cve-team commented on 2021/24xxx/CVE-2021-24164.json
>  {
[] is too short

2021-04-02 13:20 UTC, cve-team commented on 2021/24xxx/CVE-2021-24167.json
>  {
[] is too short

2021-04-04 09:05 UTC, ethicalhack3r commented
This should now be ready to merge

2021-04-05 16:41 UTC, cristina479 commented on 2021/24xxx/CVE-2021-24153.json
> +        "value": "The changelog reads: \"Fixes a stored XSS issue in the Yoast SEO metabox. Thanks Hammad Shamsi for reporting and responsibly disclosing this issue.\""
Should remove "The changelog reads:" and the discoverer of the vulnerability. CVE policy does not give credit to discoverers in the CVE description. Therefore, "hanks Hammad Shamsi for reporting and responsibly disclosing this issue." must be removed.

2021-04-05 16:41 UTC, cristina479 commented on 2021/24xxx/CVE-2021-24160.json
> +        "value": "\"A subscriber could upload zip archives containing malicious PHP files that would get extracted to the /rmp-menu// directory. These files could then be accessed via the front end o
Remove \" ... \" characters

2021-04-05 16:41 UTC, cristina479 commented on 2021/24xxx/CVE-2021-24160.json
> +                }
Should be removed if no product is provided

2021-04-05 16:41 UTC, cristina479 commented on 2021/24xxx/CVE-2021-24160.json
> +        "value": "\"A subscriber could upload zip archives containing malicious PHP files that would get extracted to the /rmp-menu// directory. These files could then be accessed via the front end o
The description must, at least, have the product name.

2021-04-05 16:41 UTC, cristina479 commented on 2021/24xxx/CVE-2021-24161.json
> +                }
Should be removed if no product is provided

2021-04-05 16:41 UTC, cristina479 commented on 2021/24xxx/CVE-2021-24161.json
> +        "value": "\"Attackers could craft a request and trick an administrator into uploading a zip archive containing malicious PHP files. The attacker could then access those files to achieve remot
The description must, at least, have the product name, and “\” … “\” characters should be removed.

2021-04-05 16:41 UTC, cristina479 commented on 2021/24xxx/CVE-2021-24162.json
> +                }
Should be removed if no product is provided

2021-04-05 16:41 UTC, cristina479 commented on 2021/24xxx/CVE-2021-24162.json
> +        "value": "\"Attackers could craft a request and trick an administrator into importing all new settings. These settings could be modified to include malicious JavaScript, therefore allowing an
The description must, at least, have the product name, and “\” … “\” characters should be removed.

2021-04-05 16:41 UTC, cristina479 commented on 2021/24xxx/CVE-2021-24164.json
> +        "value": "Low-level users, such as subscribers, were able to trigger the action, wp_ajax_nf_oauth, and retrieve the connection url needed to establish a connection. They could also retrieve t
The description must, at least, have the product name

2021-04-05 16:41 UTC, cristina479 commented on 2021/24xxx/CVE-2021-24165.json
> +        "value": "The wp_ajax_nf_oauth_connect AJAX action was vulnerable to open redirect due to the use of a user supplied redirect parameter and no protection in place."
The description must, at least, have the product name

2021-04-05 18:30 UTC, merged