Update CVE-2020-13671.json
CVEProject/cvelist pull request #148
Opened 2020-11-18 18:31 UTC by mlhess

2020-11-18 18:35 UTC, cve-team requested changes
Auto validation errors:

2020-11-18 18:35 UTC, cve-team commented on 2020/13xxx/CVE-2020-13671.json
>  {
{} is not allowed for {'vendor': {'vendor_data': [{'vendor_name': 'Drupal ', 'product': {'product_data': [{'product_name': 'Drupal Core', 'version': {'version_data': [{'version_name': '9.0', 'version_affected': '<', 'version_value': '9.0.8', 'platform': ''}, {'version_name': '8.9', 'version_affected': '<', 'version_value': '8.9.9', 'platform': ''}, {'version_name': '8.8', 'version_affected': '<', 'version_value': '8.8.11', 'platform': ''}, {'version_name': '7', 'version_affected': '<', 'version_value': '7.74', 'platform': ''}]}}]}}]}}

2020-11-18 18:35 UTC, cve-team commented on 2020/13xxx/CVE-2020-13671.json
>  {
{} is not allowed for {'problemtype_data': [{'description': [{'lang': 'eng', 'value': 'Remote code execution'}]}]}

2020-11-18 18:35 UTC, cve-team commented on 2020/13xxx/CVE-2020-13671.json
>  {
{} is not allowed for {'reference_data': [{'refsource': 'CONFIRM', 'url': 'https://www.drupal.org/sa-core-2020-012', 'name': ''}]}

2020-11-18 22:30 UTC, cve-team requested changes
Auto validation errors:

2020-11-18 22:30 UTC, cve-team commented on 2020/13xxx/CVE-2020-13671.json
>  {
A language tag was used multiple times: description.

2020-11-19 02:10 UTC, cve-team commented on 2020/13xxx/CVE-2020-13671.json
> +        "lang": "eng",
The system doesn't know how to handle two descriptions for the same language.  You will need to consolidate the descriptions.

2020-11-19 14:00 UTC, cve-team commented on 2020/13xxx/CVE-2020-13671.json
> +        "name": ""
The name field for the reference cannot be blank if you are using a refsource.

2020-11-19 14:54 UTC, cristina479 commented
@mlhess Please resolve the auto validation errors so we can process your request. Thank you!

2020-11-19 17:15 UTC, cve-team requested changes
Auto validation errors:

2020-11-19 17:15 UTC, cve-team commented on 2020/13xxx/CVE-2020-13671.json
>  {
MISC or CONFIRM, but name != url for reference.

2020-11-19 17:17 UTC, cristina479 commented on 2020/13xxx/CVE-2020-13671.json
>  {
I think removing the `name` field will resolve this issue.

2020-11-19 17:24 UTC, cristina479 commented on 2020/13xxx/CVE-2020-13671.json
> +        "value": "This issue affects:\nDrupal  Drupal Core\n9.0 versions prior to 9.0.8;\n8.9 versions prior to 8.9.9;\n8.8 versions prior to 8.8.11;\n7 versions prior to 7.74."
What is the issue? The description should have at a minimum a vulnerability (i.e., problem type) with sufficient detail as to demonstrate that the vulnerability is unique.

2020-11-20 15:45 UTC, merged