Update CVE-2021-29101.json
CVEProject/cvelist pull request #1518
Opened 2021-05-03 18:42 UTC by RandallWilliams

Esri allocates CVE-2021-29101

2021-05-03 18:45 UTC, cve-team requested changes
Auto validation errors:

2021-05-03 18:45 UTC, cve-team commented on 2021/29xxx/CVE-2021-29101.json
>  {
An exception of type JSONDecodeError occurred. Arguments:

2021-05-03 18:45 UTC, cve-team commented on 2021/29xxx/CVE-2021-29101.json
>  {
('Extra data: line 100 column 1 (char 3316)',)

2021-05-04 13:24 UTC, RandallWilliams commented
@cve-team please review and merge.

2021-05-05 18:25 UTC, merged