Add CVE-2021-28689 XSA-370
CVEProject/cvelist pull request #1524
Opened 2021-05-04 14:08 UTC by xen-project-security-team

Signed-off-by: Ian Jackson <iwj@xenproject.org>

2021-05-04 14:10 UTC, cve-team requested changes
Auto validation errors:

2021-05-04 14:10 UTC, cve-team commented on 2021/26xxx/CVE-2021-28689.json
> +{
Expected location (2021/28xxx/CVE-2021-28689.json) of file does not match actual location (2021/26xxx/CVE-2021-28689.json)

2021-05-04 14:11 UTC, xen-project-security-team commented on 2021/26xxx/CVE-2021-28689.json
> +{
fixed

2021-05-10 15:57 UTC, xen-project-security-team commented
ping?

2021-06-10 15:28 UTC, xen-project-security-team commented
Please re-review this?

2021-06-10 15:30 UTC, cve-team requested changes
Auto validation errors:

2021-06-10 15:30 UTC, cve-team commented on 2021/28xxx/CVE-2021-28689.json
>  {
None is not of type 'string'

2021-06-10 15:30 UTC, cve-team commented on 2021/28xxx/CVE-2021-28689.json
>  {
None is not of type 'string'

2021-06-10 16:41 UTC, xen-project-security-team commented
Fixed, again, sorry.

2021-06-11 14:55 UTC, merged