Qualcomm_7-12-2021
CVEProject/cvelist pull request #2218
Opened 2021-07-12 06:11 UTC by QC-CNA

2021-07-12 06:15 UTC, cve-team requested changes
Auto validation errors:

2021-07-12 06:15 UTC, cve-team commented on 2021/1xxx/CVE-2021-1888.json
>  {
An exception of type JSONDecodeError occurred. Arguments:

2021-07-12 06:15 UTC, cve-team commented on 2021/1xxx/CVE-2021-1888.json
>  {
('Invalid control character at: line 43 column 24 (char 2815)',)

2021-07-12 06:15 UTC, cve-team commented on 2021/1xxx/CVE-2021-1890.json
>  {
An exception of type JSONDecodeError occurred. Arguments:

2021-07-12 06:15 UTC, cve-team commented on 2021/1xxx/CVE-2021-1890.json
>  {
('Invalid control character at: line 43 column 24 (char 2841)',)

2021-07-12 06:15 UTC, cve-team commented on 2021/1xxx/CVE-2021-1931.json
>  {
An exception of type JSONDecodeError occurred. Arguments:

2021-07-12 06:15 UTC, cve-team commented on 2021/1xxx/CVE-2021-1931.json
>  {
('Invalid control character at: line 43 column 24 (char 2469)',)

2021-07-12 06:15 UTC, cve-team commented on 2021/1xxx/CVE-2021-1965.json
>  {
An exception of type JSONDecodeError occurred. Arguments:

2021-07-12 06:15 UTC, cve-team commented on 2021/1xxx/CVE-2021-1965.json
>  {
('Invalid control character at: line 43 column 24 (char 2476)',)

2021-07-13 05:29 UTC, QC-CNA commented on 2021/1xxx/CVE-2021-1888.json
>  {
Updated Qualcomm_7-12-2021 branch. please check and let us know if any issues

2021-07-13 05:29 UTC, QC-CNA commented on 2021/1xxx/CVE-2021-1888.json
>  {
Updated Qualcomm_7-12-2021 branch. please check and let us know if any issues

2021-07-13 05:30 UTC, QC-CNA commented on 2021/1xxx/CVE-2021-1890.json
>  {
Updated Qualcomm_7-12-2021 branch. please check and let us know if any issues

2021-07-13 05:30 UTC, QC-CNA commented on 2021/1xxx/CVE-2021-1931.json
>  {
Updated Qualcomm_7-12-2021 branch. please check and let us know if any issues

2021-07-13 05:30 UTC, QC-CNA commented on 2021/1xxx/CVE-2021-1965.json
>  {
Updated Qualcomm_7-12-2021 branch. please check and let us know if any issues

2021-07-13 05:31 UTC, QC-CNA commented on 2021/1xxx/CVE-2021-1965.json
>  {
Updated Qualcomm_7-12-2021 branch. please check and let us know if any issues

2021-07-13 05:31 UTC, merged