ZDI assigns the following CVEs:
CVEProject/cvelist pull request #2413
Opened 2021-08-03 16:42 UTC by zdi-team

M  34xxx/CVE-2021-34831.json
M  34xxx/CVE-2021-34832.json
M  34xxx/CVE-2021-34833.json
M  34xxx/CVE-2021-34834.json
M  34xxx/CVE-2021-34835.json
M  34xxx/CVE-2021-34836.json
M  34xxx/CVE-2021-34837.json
M  34xxx/CVE-2021-34838.json
M  34xxx/CVE-2021-34839.json
M  34xxx/CVE-2021-34840.json
M  34xxx/CVE-2021-34841.json
M  34xxx/CVE-2021-34842.json
M  34xxx/CVE-2021-34843.json
M  34xxx/CVE-2021-34844.json
M  34xxx/CVE-2021-34845.json
M  34xxx/CVE-2021-34846.json
M  34xxx/CVE-2021-34847.json
M  34xxx/CVE-2021-34848.json
M  34xxx/CVE-2021-34849.json
M  34xxx/CVE-2021-34850.json
M  34xxx/CVE-2021-34851.json
M  34xxx/CVE-2021-34852.json
M  34xxx/CVE-2021-34853.json

2021-08-03 16:45 UTC, cve-team requested changes
Auto validation errors:

2021-08-03 16:45 UTC, cve-team commented on 2021/34xxx/CVE-2021-34831.json
>  {
'https://www.foxit.com/support/security-bulletins.html\xa0' does not match '^(ftp|http)s?://\\S+$'

2021-08-03 16:45 UTC, cve-team commented on 2021/34xxx/CVE-2021-34832.json
>  {
'https://www.foxit.com/support/security-bulletins.html\xa0' does not match '^(ftp|http)s?://\\S+$'

2021-08-03 16:45 UTC, cve-team commented on 2021/34xxx/CVE-2021-34833.json
>  {
'https://www.foxit.com/support/security-bulletins.html\xa0' does not match '^(ftp|http)s?://\\S+$'

2021-08-03 16:45 UTC, cve-team commented on 2021/34xxx/CVE-2021-34834.json
>  {
'https://www.foxit.com/support/security-bulletins.html\xa0' does not match '^(ftp|http)s?://\\S+$'

2021-08-03 16:45 UTC, cve-team commented on 2021/34xxx/CVE-2021-34835.json
>  {
'https://www.foxit.com/support/security-bulletins.html\xa0' does not match '^(ftp|http)s?://\\S+$'

2021-08-03 16:45 UTC, cve-team commented on 2021/34xxx/CVE-2021-34836.json
>  {
'https://www.foxit.com/support/security-bulletins.html\xa0' does not match '^(ftp|http)s?://\\S+$'

2021-08-03 16:45 UTC, cve-team commented on 2021/34xxx/CVE-2021-34837.json
>  {
'https://www.foxit.com/support/security-bulletins.html\xa0' does not match '^(ftp|http)s?://\\S+$'

2021-08-03 16:45 UTC, cve-team commented on 2021/34xxx/CVE-2021-34838.json
>  {
'https://www.foxit.com/support/security-bulletins.html\xa0' does not match '^(ftp|http)s?://\\S+$'

2021-08-03 16:45 UTC, cve-team commented on 2021/34xxx/CVE-2021-34839.json
>  {
'https://www.foxit.com/support/security-bulletins.html\xa0' does not match '^(ftp|http)s?://\\S+$'

2021-08-03 16:45 UTC, cve-team commented on 2021/34xxx/CVE-2021-34840.json
>  {
'https://www.foxit.com/support/security-bulletins.html\xa0' does not match '^(ftp|http)s?://\\S+$'

2021-08-03 16:45 UTC, cve-team commented on 2021/34xxx/CVE-2021-34841.json
>  {
'https://www.foxit.com/support/security-bulletins.html\xa0' does not match '^(ftp|http)s?://\\S+$'

2021-08-03 16:45 UTC, cve-team commented on 2021/34xxx/CVE-2021-34842.json
>  {
'https://www.foxit.com/support/security-bulletins.html\xa0' does not match '^(ftp|http)s?://\\S+$'

2021-08-03 16:45 UTC, cve-team commented on 2021/34xxx/CVE-2021-34843.json
>  {
'https://www.foxit.com/support/security-bulletins.html\xa0' does not match '^(ftp|http)s?://\\S+$'

2021-08-03 16:45 UTC, cve-team commented on 2021/34xxx/CVE-2021-34844.json
>  {
'https://www.foxit.com/support/security-bulletins.html\xa0' does not match '^(ftp|http)s?://\\S+$'

2021-08-03 16:45 UTC, cve-team commented on 2021/34xxx/CVE-2021-34845.json
>  {
'https://www.foxit.com/support/security-bulletins.html\xa0' does not match '^(ftp|http)s?://\\S+$'

2021-08-03 16:45 UTC, cve-team commented on 2021/34xxx/CVE-2021-34846.json
>  {
'https://www.foxit.com/support/security-bulletins.html\xa0' does not match '^(ftp|http)s?://\\S+$'

2021-08-03 16:45 UTC, cve-team commented on 2021/34xxx/CVE-2021-34847.json
>  {
'https://www.foxit.com/support/security-bulletins.html\xa0' does not match '^(ftp|http)s?://\\S+$'

2021-08-03 16:45 UTC, cve-team commented on 2021/34xxx/CVE-2021-34848.json
>  {
'https://www.foxit.com/support/security-bulletins.html\xa0' does not match '^(ftp|http)s?://\\S+$'

2021-08-03 16:45 UTC, cve-team commented on 2021/34xxx/CVE-2021-34849.json
>  {
'https://www.foxit.com/support/security-bulletins.html\xa0' does not match '^(ftp|http)s?://\\S+$'

2021-08-03 16:45 UTC, cve-team commented on 2021/34xxx/CVE-2021-34850.json
>  {
'https://www.foxit.com/support/security-bulletins.html\xa0' does not match '^(ftp|http)s?://\\S+$'

2021-08-03 16:45 UTC, cve-team commented on 2021/34xxx/CVE-2021-34851.json
>  {
'https://www.foxit.com/support/security-bulletins.html\xa0' does not match '^(ftp|http)s?://\\S+$'

2021-08-03 16:45 UTC, cve-team commented on 2021/34xxx/CVE-2021-34852.json
>  {
'https://www.foxit.com/support/security-bulletins.html\xa0' does not match '^(ftp|http)s?://\\S+$'

2021-08-03 16:45 UTC, cve-team commented on 2021/34xxx/CVE-2021-34853.json
>  {
'https://www.foxit.com/support/security-bulletins.html\xa0' does not match '^(ftp|http)s?://\\S+$'

2021-08-03 19:53 UTC, zdi-team commented on 2021/34xxx/CVE-2021-34831.json
>  {
good catch, will push a commit

2021-08-03 21:06 UTC, zdi-team commented on 2021/34xxx/CVE-2021-34831.json
>  {
what language is doing this check? Python? We ask because we're seeing different behavior depending on language (even tho they are all PCRE-based) and string encoding.

2021-08-04 15:14 UTC, zdi-team commented
Fixed with a1c7b51c902fa38740a2326e41cbc7fd59ab09d8

2021-08-04 15:16 UTC, merged