Add CVE-2021-39181 for GHSA-596v-3gwh-2m9w
CVEProject/cvelist pull request #2738
Opened 2021-08-31 18:11 UTC by shelbyc

Add CVE-2021-39181 for GHSA-596v-3gwh-2m9w

2021-08-31 18:15 UTC, cve-team requested changes
Auto validation errors:

2021-08-31 18:15 UTC, cve-team commented on 2021/39xxx/CVE-2021-39181.json
>  {
'https://jira.openolat.org/browse/OO-5548 ' does not match '^(ftp|http)s?://\\S+$'

2021-09-01 19:42 UTC, shelbyc commented on 2021/39xxx/CVE-2021-39181.json
>  {
Removed unnecessary space at the end of the URI

2021-09-01 19:43 UTC, shelbyc commented on 2021/39xxx/CVE-2021-39181.json
>  {
Removed space from the end of the URI

2021-09-01 19:45 UTC, merged