Add descriptions for OpenNMS issues from 2016
CVEProject/cvelist pull request #2841
Opened 2021-09-11 00:05 UTC by todb-r7

Thanks @mkienow-r7 for noticing these never got published!

2021-09-11 00:10 UTC, cve-team requested changes
Auto validation errors:

2021-09-11 00:10 UTC, cve-team commented on 2016/6xxx/CVE-2016-6555.json
>  {
CNA(s) of user (rapid7) do not match owning CNA.

2021-09-11 00:10 UTC, cve-team commented on 2016/6xxx/CVE-2016-6556.json
>  {
CNA(s) of user (rapid7) do not match owning CNA.

2021-09-11 13:02 UTC, todb-r7 commented
Oh! I bet these came from before we were a CNA! I'll bug CERT/CC about this and changing ownership and all that.

2021-09-21 14:41 UTC, zmanion commented
How do we change owning CNA? CERT/CC relinquishes ownership to Rapid7. Or we can take Rapid7's content and submit it as ours, which seems awkward and sub-optimal.

2021-09-21 14:51 UTC, todb-r7 commented
I will happily take ownership of these CVE IDs, @cve-team !

2021-09-24 21:02 UTC, merged