Updated CVE-2019-14822's assignee and refs
CVEProject/cvelist pull request #2864
Opened 2019-12-02 07:41 UTC by darunesh-RH

2019-12-02 07:45 UTC, cve-team commented on 2019/14xxx/CVE-2019-14822.json
>      "data_version": "4.0",
Invalid JSON file

2020-02-19 21:43 UTC, cristina479 commented
Red Hat CNA,

The JSON submitted doesn't conform with the current JSON schema. Can you make the corrections necessary in order to publish this CVE ID to the CVE List?

Thank you,
Cristina

2020-05-29 18:33 UTC, cristina479 commented
Dear darunesh-RH,

Can you include the requested changes to the `version_data` and `description` fields?

2020-06-25 14:20 UTC, cristina479 commented
> Dear darunesh-RH,
> 
> Can you include the requested changes to the `version_data` and `description` fields?

This is a friendly reminder that we are still waiting on these changes.

2020-08-27 16:22 UTC, guitos commented
@cristina479, the CVE-2019-14822 was updated via web from to include version information.

2020-08-31 19:01 UTC, guitos commented
@cristina479, is there anything that needs to be updated for CVE-2019-14822? If not, can you please close this merge request?

2020-09-04 13:20 UTC, cve-team requested changes
Auto validation errors:

2020-09-04 13:20 UTC, cve-team commented on 2019/14xxx/CVE-2019-14822.json
>      "data_version": "4.0",
An exception of type JSONDecodeError occurred. Arguments:

2020-09-04 13:20 UTC, cve-team commented on 2019/14xxx/CVE-2019-14822.json
>      "data_version": "4.0",
("Expecting ',' delimiter: line 59 column 17 (char 1818)",)

2020-09-04 13:25 UTC, fabioolive commented on 2019/14xxx/CVE-2019-14822.json
>      "data_version": "4.0",
Fixed.

2020-09-04 13:25 UTC, fabioolive commented on 2019/14xxx/CVE-2019-14822.json
>      "data_version": "4.0",
Fixed.

2020-09-04 13:35 UTC, fabioolive commented
@cve-team @cristina479 Hi, can we get a final review and merge of this branch? Thank you!

2020-10-21 13:15 UTC, closed without merging