Add CVE-2021-39222 for GHSA-xhxq-f4vg-jw5g
CVEProject/cvelist pull request #3230
Opened 2021-10-25 19:25 UTC by shelbyc

Add CVE-2021-39222 for GHSA-xhxq-f4vg-jw5g

2021-10-25 19:30 UTC, cve-team requested changes
Auto validation errors:

2021-10-25 19:30 UTC, cve-team commented on 2021/39xxx/CVE-2021-39222.json
>  {
'ttps://hackerone.com/reports/1135481' does not match '^(ftp|http)s?://\\S+$'

2021-10-29 11:21 UTC, ktodd229 commented
Please review the necessary changes, fix, and resubmit.

2021-11-15 18:27 UTC, shelbyc commented on 2021/39xxx/CVE-2021-39222.json
>  {
Corrected to start with https

2021-11-15 18:27 UTC, shelbyc reviewed
Corrected the typo (ttps instead of https in URL)

2021-11-15 18:30 UTC, merged