Modify CVE-2021-41145 for GHSA-jvpq-23v4-gp3m
CVEProject/cvelist pull request #3239
Opened 2021-10-25 22:12 UTC by shelbyc

Modify CVE-2021-41145 for GHSA-jvpq-23v4-gp3m

2021-10-25 22:15 UTC, cve-team requested changes
Auto validation errors:

2021-10-25 22:15 UTC, cve-team commented on 2021/41xxx/CVE-2021-41145.json
>  {
'ASSIGNER' is a required property

2021-10-25 22:15 UTC, cve-team commented on 2021/41xxx/CVE-2021-41145.json
>  {
'vendor_name' is a required property

2021-10-25 22:15 UTC, cve-team commented on 2021/41xxx/CVE-2021-41145.json
>  {
'product_name' is a required property

2021-10-25 22:15 UTC, cve-team commented on 2021/41xxx/CVE-2021-41145.json
>  {
'version_value' is a required property

2021-10-29 11:21 UTC, ktodd229 commented
Please review the necessary changes, fix, and resubmit.

2021-11-15 18:43 UTC, shelbyc commented on 2021/41xxx/CVE-2021-41145.json
>  {
Pushed modified json file that should correct the issue.

2021-11-15 18:44 UTC, shelbyc commented on 2021/41xxx/CVE-2021-41145.json
>  {
Pushed modified json file that should correct the issue.

2021-11-15 18:44 UTC, shelbyc commented on 2021/41xxx/CVE-2021-41145.json
>  {
Pushed modified json file that should correct the issue.

2021-11-15 20:53 UTC, anthnysingleton commented
Thank you for your submission. Expect CVE-2021-41145 to be published on http://cve.mitre.org in the next few hours.

2021-11-15 20:55 UTC, merged