6 FatPipe CVE IDs
CVEProject/cvelist pull request #3715
Opened 2021-12-10 03:51 UTC by zmanion

Updating CVE-2021-27860 and adding 5 other FatPipe CVE IDs. cc @sei-vsarvepalli.

2021-12-10 03:55 UTC, cve-team requested changes
Auto validation errors:

2021-12-10 03:55 UTC, cve-team commented on 2021/27xxx/CVE-2021-27856.json
>  {
'problemtype' is a required property

2021-12-10 13:04 UTC, zmanion commented on 2021/27xxx/CVE-2021-27856.json
>  {
Fixed in https://github.com/CVEProject/cvelist/pull/3715/commits/7f6e785d430425b527782b8ec350c283baeca1f4

2021-12-10 13:05 UTC, cve-team commented
WARNING: Github identified an issue when verifying the signature - unknown_key

2021-12-15 16:23 UTC, anthnysingleton commented
Hey @zmanion, Can you take a look at this PR and resolve the Merge Conflicts. Once completed we can get this merged into the list. Thanks.

2021-12-15 19:50 UTC, zmanion commented
> Hey @zmanion, Can you take a look at this PR and resolve the Merge Conflicts. Once completed we can get this merged into the list. Thanks.

Not sure how to do this, I don't have privileges to "Mark as resolved." The inbound 2021/27xxx/CVE-2021-27860.json from this PR should overwrite whatever is in master.

2021-12-15 19:54 UTC, ahouseholder commented
fixed merge conflict per Art's request

> > Hey @zmanion, Can you take a look at this PR and resolve the Merge Conflicts. Once completed we can get this merged into the list. Thanks.
> 
> Not sure how to do this, I don't have privileges to "Mark as resolved." The inbound 2021/27xxx/[CVE-2021-27860](https://github.com/advisories/GHSA-hfgw-xgjr-v384).json from this PR should overwrite whatever is in master.

2021-12-15 19:55 UTC, merged