XSA-391 CVE-2021-28711 CVE-2021-28712 CVE-2021-28713
CVEProject/cvelist pull request #3831
Opened 2021-12-20 12:45 UTC by xen-project-security-team

XSA-391 CVE-2021-28711 CVE-2021-28712 CVE-2021-28713

CVE data entry for:
  CVE-2021-28711

(This MR was automatically generated by the Xen Project Security Team's
xensec-internal-tools.  Please let us know if anything could be better.)
  CVE-2021-28712

(This MR was automatically generated by the Xen Project Security Team's
xensec-internal-tools.  Please let us know if anything could be better.)
  CVE-2021-28713

(This MR was automatically generated by the Xen Project Security Team's
xensec-internal-tools.  Please let us know if anything could be better.)

2021-12-20 12:50 UTC, cve-team requested changes
Auto validation errors:

2021-12-20 12:50 UTC, cve-team commented on 2021/28xxx/CVE-2021-28711.json
>  {
{'version_affected': '?', 'version_value': 'consult Xen advisory XSA-391'} is not of type 'array'

2021-12-20 12:50 UTC, cve-team commented on 2021/28xxx/CVE-2021-28712.json
>  {
{'version_affected': '?', 'version_value': 'consult Xen advisory XSA-391'} is not of type 'array'

2021-12-20 12:50 UTC, cve-team commented on 2021/28xxx/CVE-2021-28713.json
>  {
{'version_affected': '?', 'version_value': 'consult Xen advisory XSA-391'} is not of type 'array'

2021-12-20 18:47 UTC, anthnysingleton commented
Hello @xen-project-security-team ,

Can you review your PR and adjust your "affects" object. You can use the [examples provided in V4](https://github.com/CVEProject/cve-schema/blob/master/schema/v4.0/DRAFT-JSON-file-format-v4.md#examples) for guidance. I have also pasted the object below

```
"affects": {
			"vendor": {
				"vendor_data": [
					{
						"vendor_name": " ",
						"product": {
							"product_data": [
								{
									"product_name": "sha-1",
									"version": {
										"version_data": [
											{
												"version_value": " "
											}
										]
									}
								}
							]
						}
					}
				]
			}
		}
```

2021-12-28 16:38 UTC, anthnysingleton commented
@xen-project-security-team we are still waiting for the corrections to be made so we can process your request.

2022-01-04 16:58 UTC, ijackson commented
@anthnysingleton Oops, thanks, I have fixed the syntax.

2022-01-05 16:15 UTC, merged