Add CVE-2021-4175 for 8a7d16e0-9a46-4710-a029-c89c33c01528
CVEProject/cvelist pull request #3869
Opened 2021-12-27 05:39 UTC by JamieSlome

Add CVE-2021-4175 for [8a7d16e0-9a46-4710-a029-c89c33c01528](https://huntr.dev/bounties/8a7d16e0-9a46-4710-a029-c89c33c01528) @huntr-helper

2021-12-27 05:40 UTC, cve-team requested changes
Auto validation errors:

2021-12-27 05:40 UTC, cve-team commented on 2021/4xxx/CVE-2021-4175.json
> +{
None is not of type 'string'

2021-12-28 16:36 UTC, anthnysingleton commented
@JamieSlome Please resolution the validation issues and the merge conflict. Once resolved we can process and merge request.

2021-12-29 14:35 UTC, merged

2021-12-29 14:37 UTC, JamieSlome commented
@anthnysingleton - sorted! ❤️