Add CVE-2021-4176 for 8b531ae9-2d36-43ff-af33-4d81acfb2f27
CVEProject/cvelist pull request #3870
Opened 2021-12-27 05:48 UTC by JamieSlome

Add CVE-2021-4176 for [8b531ae9-2d36-43ff-af33-4d81acfb2f27](https://huntr.dev/bounties/8b531ae9-2d36-43ff-af33-4d81acfb2f27) @huntr-helper

2021-12-27 05:50 UTC, cve-team requested changes
Auto validation errors:

2021-12-27 05:50 UTC, cve-team commented on 2021/4xxx/CVE-2021-4176.json
> +{
None is not of type 'string'

2021-12-28 16:37 UTC, anthnysingleton commented
@JamieSlome Please resolution the validation issues and the merge conflict. Once resolved we can process and merge request.

2021-12-29 14:36 UTC, JamieSlome commented
@anthnysingleton - sorted! ❤️

2021-12-29 14:40 UTC, merged