Qualcomm_12-27-2021
CVEProject/cvelist pull request #3872
Opened 2021-12-27 10:33 UTC by QC-CNA

2021-12-28 16:45 UTC, cve-team requested changes
Auto validation errors:

2021-12-28 16:45 UTC, cve-team commented on 2021/30xxx/CVE-2021-35093.json
> +{
Expected location (2021/35xxx/CVE-2021-35093.json) of file does not match actual location (2021/30xxx/CVE-2021-35093.json)

2021-12-28 17:32 UTC, anthnysingleton commented
@QC-CNA Please resolve the Auto Validation errors. Once resolved we can move forward and process the request.

2022-01-03 07:24 UTC, QC-CNA commented
Validation errors resolved for CVE-2021-35093.json
please let us know if anything else needs to be updated.

2022-01-03 07:26 UTC, merged

2022-01-03 07:26 UTC, QC-CNA commented
Hello ,

Validation errors are resolved. Please let us know if any additional change required

Regards
Sameesh


From: anthnysingleton ***@***.***>
Sent: Tuesday, December 28, 2021 11:03 PM
To: CVEProject/cvelist ***@***.***>
Cc: security.cna ***@***.***>; Mention ***@***.***>
Subject: Re: [CVEProject/cvelist] Qualcomm_12-27-2021 (PR #3872)


WARNING: This email originated from outside of Qualcomm. Please be wary of any links or attachments, and do not enable macros.

@QC-CNA<https://github.com/QC-CNA> Please resolve the Auto Validation errors. Once resolved we can move forward and process the request.

—
Reply to this email directly, view it on GitHub<https://github.com/CVEProject/cvelist/pull/3872#issuecomment-1002210792>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AJ3BBXMKDJRQ5NA2DDWAYFLUTHYC7ANCNFSM5K2ECREA>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>