Publish CVE-2021-41043
CVEProject/cvelist pull request #3904
Opened 2021-12-30 22:59 UTC by infrastation

2021-12-30 23:00 UTC, cve-team commented
infrastation is not recognized currently as an account participating in the Git Pilot. To ensure timely processing of your pull request, please contact the CVE Team using either the CVE Request web form (https://cveform.mitre.org/) or an email (cve@mitre.org) and confirm your identity.

2021-12-30 23:32 UTC, infrastation commented
Apparently, the suggested e-mail address is **not** a valid point of contact:
> This email address is not monitored.
> To contact the CVE Program, use https://cveform.mitre.org and choose “Other” from the dropdown menu.

2022-01-03 20:45 UTC, cve-team requested changes
Auto validation errors:

2022-01-03 20:45 UTC, cve-team commented on 2021/41xxx/CVE-2021-41043.json
>      "data_version": "4.0",
MISC or CONFIRM, but name != url for reference.

2022-01-03 22:00 UTC, cve-team requested changes
Auto validation errors:

2022-01-03 22:00 UTC, cve-team commented on 2021/41xxx/CVE-2021-41043.json
>      "data_version": "4.0",
An exception of type JSONDecodeError occurred. Arguments:

2022-01-03 22:00 UTC, cve-team commented on 2021/41xxx/CVE-2021-41043.json
>      "data_version": "4.0",
('Expecting property name enclosed in double quotes: line 64 column 13 (char 1900)',)

2022-01-04 12:50 UTC, infrastation commented
Since the script is not flagging any more issues, I suggest to merge this pull requests right away. Alternatively, someone could fix the broken script so it re-validates the file again, and see what the results are.

2022-01-05 11:10 UTC, infrastation commented
It looks like this repository is not actually manned by any member of MITRE staff.

2022-01-05 11:35 UTC, merged

2022-01-05 11:39 UTC, infrastation commented
Oh, thank you!