ZDI assigns the following CVEs:
CVEProject/cvelist pull request #4040
Opened 2022-01-13 23:33 UTC by zdi-team

A  CVE-2021-34865.json
A  CVE-2021-34866.json
A  CVE-2021-34867.json
A  CVE-2021-34868.json
A  CVE-2021-34869.json
A  CVE-2021-34870.json

2022-01-13 23:35 UTC, cve-team requested changes
Auto validation errors:

2022-01-13 23:35 UTC, cve-team commented on CVE-2021-34865.json
> +{
Expected location (2021/34xxx/CVE-2021-34865.json) of file does not match actual location (CVE-2021-34865.json)

2022-01-13 23:35 UTC, cve-team commented on CVE-2021-34866.json
> +{
Expected location (2021/34xxx/CVE-2021-34866.json) of file does not match actual location (CVE-2021-34866.json)

2022-01-13 23:35 UTC, cve-team commented on CVE-2021-34867.json
> +{
Expected location (2021/34xxx/CVE-2021-34867.json) of file does not match actual location (CVE-2021-34867.json)

2022-01-13 23:35 UTC, cve-team commented on CVE-2021-34868.json
> +{
Expected location (2021/34xxx/CVE-2021-34868.json) of file does not match actual location (CVE-2021-34868.json)

2022-01-13 23:35 UTC, cve-team commented on CVE-2021-34869.json
> +{
Expected location (2021/34xxx/CVE-2021-34869.json) of file does not match actual location (CVE-2021-34869.json)

2022-01-13 23:35 UTC, cve-team commented on CVE-2021-34870.json
> +{
Expected location (2021/34xxx/CVE-2021-34870.json) of file does not match actual location (CVE-2021-34870.json)

2022-01-19 21:02 UTC, anthnysingleton commented
@zdi-team ,

Please review and correct the issues listed from the Auto validation checker. Once corrected we can proceed with the process of merging these changes into the main list. 

Thanks,
CVE Content Team

2022-01-25 15:27 UTC, zdi-team commented on CVE-2021-34866.json
> +{
moved to proper location and squashed commit

2022-01-25 15:28 UTC, zdi-team commented on CVE-2021-34867.json
> +{
moved to proper location and squashed commit

2022-01-25 15:28 UTC, zdi-team commented on CVE-2021-34869.json
> +{
moved to proper location and squashed commit

2022-01-25 15:28 UTC, zdi-team commented on CVE-2021-34868.json
> +{
moved to proper location and squashed commit

2022-01-25 15:28 UTC, zdi-team commented on CVE-2021-34870.json
> +{
moved to proper location and squashed commit

2022-01-25 15:29 UTC, zdi-team commented
> @zdi-team ,
> 
> Please review and correct the issues listed from the Auto validation checker. Once corrected we can proceed with the process of merging these changes into the main list.
> 
> Thanks, CVE Content Team



> @zdi-team ,
> 
> Please review and correct the issues listed from the Auto validation checker. Once corrected we can proceed with the process of merging these changes into the main list.
> 
> Thanks, CVE Content Team

Done

2022-01-25 15:30 UTC, merged