SHIELD_CVEs_Jan_2022_2 (CVE-2021-1106 thru CVE-2021-2021-1108)
CVEProject/cvelist pull request #4120
Opened 2022-01-18 22:58 UTC by PSIRT-NVIDIA

SHIELD_CVEs_Jan_2022_2 (CVE-2021-1106 thru CVE-2021-2021-1108)

2022-01-18 23:00 UTC, cve-team requested changes
Auto validation errors:

2022-01-18 23:00 UTC, cve-team commented on 2021/1xxx/CVE-2021-1106.json
>                      "product": {
'version_value' is a required property

2022-01-18 23:00 UTC, cve-team commented on 2021/1xxx/CVE-2021-1106.json
>                      "product": {
'version_value' is a required property

2022-01-18 23:00 UTC, cve-team commented on 2021/1xxx/CVE-2021-1107.json
>                      "product": {
'version_value' is a required property

2022-01-18 23:00 UTC, cve-team commented on 2021/1xxx/CVE-2021-1107.json
>                      "product": {
'version_value' is a required property

2022-01-18 23:00 UTC, cve-team commented on 2021/1xxx/CVE-2021-1108.json
>                  {
'version_value' is a required property

2022-01-18 23:00 UTC, cve-team commented on 2021/1xxx/CVE-2021-1108.json
>                  {
'version_value' is a required property

2022-01-18 23:04 UTC, PSIRT-NVIDIA commented
re-submitted, the file with changes

2022-01-19 14:31 UTC, PSIRT-NVIDIA commented
Can you provide the status for the re-submitted files submission?

2022-01-19 16:57 UTC, anthnysingleton commented
CVE Records have been pulled in and Processed. This PR will be merged shortly.

2022-01-19 17:00 UTC, merged

2022-01-19 17:01 UTC, PSIRT-NVIDIA commented
Thanks for the update! 

Milind