Delete CVE-2022-22122
CVEProject/cvelist pull request #4180
Opened 2022-01-24 10:39 UTC by hagaiwech

Committed by: Hagai Wechsler

2022-01-24 10:40 UTC, cve-team requested changes
Auto validation errors:

2022-01-24 10:40 UTC, cve-team commented on 2022/22xxx/CVE-2022-22122.json
> -{
An exception of type JSONDecodeError occurred. Arguments:

2022-01-24 10:40 UTC, cve-team commented on 2022/22xxx/CVE-2022-22122.json
> -{
('Expecting value: line 2 column 1 (char 1)',)

2022-01-24 10:47 UTC, hagaiwech commented
@cve-team This vulnerability was assigned two CVEs by different CNAs.
We as WhiteSource CNA wish to delete our CVE from the list, to prevent duplicates.

2022-01-25 16:20 UTC, anthnysingleton commented
Hello @hagaiwech,

Can you resolve the merge conflict for this PR? Also deleting the contents of the file is not the proper action to take. You should create a JSON file that validates against the [CVE_JSON_4.0_min_reject.schema](https://github.com/CVEProject/cve-schema/blob/master/schema/v4.0/CVE_JSON_4.0_min_reject.schema).

You can also use the following Description template for the Description of the record.

`** REJECT **
DO NOT USE THIS CANDIDATE NUMBER.  ConsultIDs: [ID].  Reason: This candidate is a reservation duplicate of [ID].  Notes: All CVE users should reference [ID] instead of this candidate.  All references and descriptions in this candidate have been removed to prevent accidental usage.`

Once these corrections have been made we can proceed with processing this request. 

Thanks,
CVE Content Team

2022-01-27 10:13 UTC, hagaiwech commented
Hi @anthnysingleton the JSON is now corrected. Please review our latest changes, Thanks.

2022-01-28 19:36 UTC, anthnysingleton commented
Hello @hagaiwech,

Once you resolve the merge conflict for this PR we can process the request.

Thanks,
CVE Content Team

2022-01-31 07:57 UTC, hagaiwech commented
@anthnysingleton resolved.

2022-02-02 16:20 UTC, merged