Adding Cisco CVE-2022-20680
CVEProject/cvelist pull request #4389
Opened 2022-02-03 22:17 UTC by santosomar

2022-02-03 22:20 UTC, cve-team requested changes
Auto validation errors:

2022-02-03 22:20 UTC, cve-team commented on 2022/CVE-2022-20630.json
> +{
Expected location (2022/20xxx/CVE-2022-20630.json) of file does not match actual location (2022/CVE-2022-20630.json)

2022-02-03 22:20 UTC, cve-team commented on 2022/CVE-2022-20680.json
> +{
Expected location (2022/20xxx/CVE-2022-20680.json) of file does not match actual location (2022/CVE-2022-20680.json)

2022-02-07 15:59 UTC, anthnysingleton commented
Hello @santosomar,

All 17 PR requests are waiting for you to address the validation errors. Once cleared up we can then process and merge these records. 

Thanks,
CVE Content Team

2022-02-10 17:05 UTC, anthnysingleton commented
This PR has been opened with no response from submitter for 7 days. MITRE CVE Content team has manually processed the file in order to get the information to the main list and its down stream users. 

Thanks,
CVE Content Team

2022-02-10 17:05 UTC, closed without merging