Put CVE-2018-16301 right
CVEProject/cvelist pull request #4427
Opened 2022-02-07 21:33 UTC by infrastation

See the commit message for clarifications.

2022-02-07 21:35 UTC, cve-team requested changes
Auto validation errors:

2022-02-07 21:35 UTC, cve-team commented on 2018/16xxx/CVE-2018-16301.json
>      "CVE_data_meta": {
CNA(s) of user (Tcpdump) do not match owning CNA.

2022-02-07 21:45 UTC, infrastation commented
It looks like this request will require manual merging. The CVE was assigned by MITRE before The Tcpdump Group became a CNA, so MITRE indeed is the owning CNA, yet this entry requires these corrections.

2022-02-09 17:12 UTC, anthnysingleton commented
Correct we have uploaded and process this record change request.

2022-02-09 17:12 UTC, closed without merging

2022-02-09 18:09 UTC, infrastation commented
Thank you, I see the update in git. Does the [web version](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-16301) require a manual update to synchronize?

2022-02-09 18:24 UTC, anthnysingleton commented
The record will be updated on the sites in the next few hours. No additional work needed.

2022-02-09 19:47 UTC, infrastation commented
That's grand then, thanks again.