Update CVE-2021-44142.json
CVEProject/cvelist pull request #4529
Opened 2022-02-14 20:06 UTC by jstanley10

This CVE ID may have been reserved by @zdi-team

2022-02-14 20:10 UTC, cve-team commented
jstanley10 is not recognized currently as an account participating in the Git Pilot. To ensure timely processing of your pull request, please contact the CVE Team using either the CVE Request web form (https://cveform.mitre.org/) or an email (cve@mitre.org) and confirm your identity.

2022-02-14 20:32 UTC, jstanley10 commented
Hello @cve-team, I attempted to reply with an email to cve@mitre.org and received a response that it was an unmonitored address. @zmanion can confirm I work for CERT/CC.

2022-02-14 20:37 UTC, zmanion commented
> Hello @cve-team, I attempted to reply with an email to [cve@mitre.org](mailto:cve@mitre.org) and received a response that it was an unmonitored address. @zmanion can confirm I work for CERT/CC.

Confirming that @jstanley10 works for the CERT/CC CNA and is authorized on our behalf to submit CVE content.

2022-02-15 19:59 UTC, anthnysingleton commented
Hey @zmanion and @jstanley10 ,

Thanks for your patience, I will add you to the git pilot.

Best, 
Anthony

2022-02-15 20:00 UTC, cve-team requested changes
Auto validation errors:

2022-02-15 20:00 UTC, cve-team commented on 2021/44xxx/CVE-2021-44142.json
>  {
CNA(s) of user (certcc) do not match owning CNA.

2022-02-15 20:05 UTC, cve-team requested changes
Auto validation errors:

2022-02-15 20:05 UTC, cve-team commented on 2021/44xxx/CVE-2021-44142.json
>  {
CNA(s) of user (certcc) do not match owning CNA.

2022-02-15 20:25 UTC, anthnysingleton commented
There is an assignment issue with this request. But I also need to get your signature key so you can make future PRs without issues. Can you open a request with our webform https://cveform.mitre.org/  selecting the "Other" option and supplying your signature key?

This will also start an email thread where we can discuss the other issue with this PR as well.

2022-02-15 21:25 UTC, zmanion commented
Hi @anthnysingleton,
For PGP, @jstanley10 can provide a key, but I've noticed some of my PRs getting a bad/unknown signature result from the CI, and then I didn't PGP sign a PR or two and they were accepted. So, just want to confirm that you would like PGP-signed commits and we'll do it.

2022-02-15 21:28 UTC, zmanion commented
For the CNA conflict, we expected this, we are not the requesting/assigning CNA. Not sure who is, I'm guessing ZDI or Red Hat or even someone from Samba. I look forward to the future when requesto=er/assigner is part of the JSON to save these round trips.

Not sure what the protocol is, somebody has to contact the requester/assigner and can they then allow our PR, or create their own submission in a timely manner? This has been reserved-but-public for a couple weeks which is why we chose to write it up.

2022-02-15 21:30 UTC, anthnysingleton commented
Hey @zmanion,

Yes on our end we have three keys for your zmanion account. We may want to clean that up so that we can reduce those errors. We do not require you to sign your commits but some organizations prefer to sign their commits so that is an additional step in getting into the Pilot. I remember seeing you sign a previous PR which is why I asked for @jstanley10 key. I will leave it to you to decide if you want your org and its approved submitters to sign their commits.

2022-02-15 21:34 UTC, anthnysingleton commented
> 

Yes it was assigned by RedHat. We have few options

1. Have the RedHat org "bless" this PR with a comment approving.
2. You can email Redhat/message RedHat on our Slack group where MITRE can see this agreement
3. [Official] Submit a request through the webform asking for assigning org to be changed to CERT/CC, MITRE will then reach out to RedHat for agreement.

2022-02-21 14:30 UTC, merged

2022-02-21 16:23 UTC, tausif-rh commented
> > 
> 
> Yes it was assigned by RedHat. We have few options
> 
> 1. Have the RedHat org "bless" this PR with a comment approving.
> 2. You can email Redhat/message RedHat on our Slack group where MITRE can see this agreement
> 3. [Official] Submit a request through the webform asking for assigning org to be changed to CERT/CC, MITRE will then reach out to RedHat for agreement.

Red Hat: 

We see the owning CNA now shows to be certcc. I agree to approve the PR as it's public now.

2022-02-21 17:37 UTC, zmanion commented
> I will leave it to you to decide if you want your org and its approved submitters to sign their commits.

We'd like to *not* PGP sign commits, we anticipate transition to the new services soon and sufficiently trust GitHub authentication and authorization. I can provide the list of GitHub user IDs that are authorized for the CERT/CC CNA, would you like those via the form?

2022-02-21 17:57 UTC, anthnysingleton commented
> We see the owning CNA now shows to be certcc. I agree to approve the PR as it's public now.

I changed it temporarily to get the PR processed. Thanks for replying via email @tausif-rh 

> We'd like to not PGP sign commits, we anticipate transition to the new services soon and sufficiently trust GitHub authentication and authorization. I can provide the list of GitHub user IDs that are authorized for the CERT/CC CNA, would you like those via the form?

@zmanion Yes if there are more users contributing to the GitHub Pilot please submit their information via the web form.