Reject CVE-2021-46388
CVEProject/cvelist pull request #4771
Opened 2022-03-03 16:15 UTC by CERT-VDE

2022-03-03 16:20 UTC, cve-team requested changes
Auto validation errors:

2022-03-03 16:20 UTC, cve-team commented on 2021/46xxx/CVE-2021-46388.json
>      "CVE_data_meta": {
{} is not allowed for {'vendor': {'vendor_data': [{'product': {'product_data': [{'product_name': 'WAGO 750-8212 PFC200 G2 2ETH RS', 'version': {'version_data': [{'version_value': 'Frimware version: 03.05.10(17)'}]}}]}, 'vendor_name': 'Wago'}]}}

2022-03-03 16:20 UTC, cve-team commented on 2021/46xxx/CVE-2021-46388.json
>      "CVE_data_meta": {
{} is not allowed for {'problemtype_data': [{'description': [{'lang': 'eng', 'value': 'Privilege Escalation'}]}]}

2022-03-03 16:20 UTC, cve-team commented on 2021/46xxx/CVE-2021-46388.json
>      "CVE_data_meta": {
{} is not allowed for {'reference_data': [{'name': 'http://rejected', 'refsource': 'CONFIRM', 'url': 'http://rejected'}]}

2022-03-03 16:50 UTC, cve-team requested changes
Auto validation errors:

2022-03-03 16:50 UTC, cve-team commented on 2021/46xxx/CVE-2021-46388.json
>      "CVE_data_meta": {
{} is not allowed for {'not': {}}

2022-03-03 16:50 UTC, cve-team commented on 2021/46xxx/CVE-2021-46388.json
>      "CVE_data_meta": {
{} is not allowed for {'not': {}}

2022-03-03 16:50 UTC, cve-team commented on 2021/46xxx/CVE-2021-46388.json
>      "CVE_data_meta": {
{} is not allowed for {'not': {}}

2022-03-03 16:55 UTC, cve-team requested changes
Auto validation errors:

2022-03-03 16:55 UTC, cve-team commented on 2021/46xxx/CVE-2021-46388.json
>      "CVE_data_meta": {
{} is not allowed for {}

2022-03-03 16:55 UTC, cve-team commented on 2021/46xxx/CVE-2021-46388.json
>      "CVE_data_meta": {
{} is not allowed for {}

2022-03-03 16:55 UTC, cve-team commented on 2021/46xxx/CVE-2021-46388.json
>      "CVE_data_meta": {
{} is not allowed for {}

2022-03-08 06:51 UTC, CERT-VDE commented
Hello Team,

what's missing here? After we had no success with the guide of the onboarding slides we used the JSON scheme for a reject entry, also with validation errors. Finally we used an existing reject as template and it seems the validation errors are gone.
We requested the review four days ago, are we missing something?

Thank you,

CERT@VDE/jochen

2022-03-09 06:52 UTC, closed without merging