rejecting CVE-2022-24727
CVEProject/cvelist pull request #4848
Opened 2022-03-10 18:15 UTC by taladrane

rejecting this CVE because its a duplicate of an existing CVE

2022-03-10 18:34 UTC, cve-team requested changes
Auto validation errors:

2022-03-10 18:34 UTC, cve-team commented on 2022/24xxx/CVE-2022-24727.json
>          "description_data": [
[] is too short

2022-03-10 19:24 UTC, taladrane commented on 2022/24xxx/CVE-2022-24727.json
>          "description_data": [
@cve-team can I get some additional context as to why this failed?

2022-03-10 19:57 UTC, anthnysingleton commented on 2022/24xxx/CVE-2022-24727.json
>          "description_data": [
Hello @taladrane I think you might have used the wrong json v4. Meaning this change has the STATE field set to Public which is incorrect if you want to reject this ID. 

For rejected CVE records we compare against this [CVE_JSON_4.0_min_reject.schema](https://github.com/CVEProject/cve-schema/blob/master/schema/v4.0/CVE_JSON_4.0_min_reject.schema)

Here is an example of an Record we rejected as duplicate assignment for [CVE-2021-20242](https://github.com/CVEProject/cvelist/blob/1be9b4688ed9af457faf4e3b97096896415e8cde/2021/20xxx/CVE-2021-20242.json)
```
{
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
        "ID": "CVE-2021-20242",
        "ASSIGNER": "cve@mitre.org",
        "STATE": "REJECT"
    },
    "description": {
        "description_data": [
            {
                "lang": "eng",
                "value": "** REJECT ** DO NOT USE THIS CANDIDATE NUMBER. ConsultIDs: CVE-2021-20176. Reason: This candidate is a reservation duplicate of CVE-2021-20176. Notes: All CVE users should reference CVE-2021-20176 instead of this candidate. All references and descriptions in this candidate have been removed to prevent accidental usage."
            }
        ]
    }
}
```

2022-03-10 19:59 UTC, anthnysingleton commented
Hello @taladrane I think you might have used the wrong json v4. Meaning this change has the STATE field set to Public which is incorrect if you want to reject this ID. 

For rejected CVE records we compare against this [CVE_JSON_4.0_min_reject.schema](https://github.com/CVEProject/cve-schema/blob/master/schema/v4.0/CVE_JSON_4.0_min_reject.schema)

Here is an example of an Record we rejected as duplicate assignment for [CVE-2021-20242](https://github.com/CVEProject/cvelist/blob/1be9b4688ed9af457faf4e3b97096896415e8cde/2021/20xxx/CVE-2021-20242.json)
```
{
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
        "ID": "CVE-2021-20242",
        "ASSIGNER": "cve@mitre.org",
        "STATE": "REJECT"
    },
    "description": {
        "description_data": [
            {
                "lang": "eng",
                "value": "** REJECT ** DO NOT USE THIS CANDIDATE NUMBER. ConsultIDs: CVE-2021-20176. Reason: This candidate is a reservation duplicate of CVE-2021-20176. Notes: All CVE users should reference CVE-2021-20176 instead of this candidate. All references and descriptions in this candidate have been removed to prevent accidental usage."
            }
        ]
    }
}
```

2022-03-10 20:14 UTC, taladrane commented on 2022/24xxx/CVE-2022-24727.json
>          "description_data": [
oh okay, I can make that change! I was following the section outlined [here](https://cve.mitre.org/cve/cna/CNA_Processes.pptx) (on the CNA processes section of the [Resources](https://www.cve.org/ResourcesSupport/Resources)) tab that said the following on slide 39:
>Rejection Process:
>- Update the Description saying that the CVE ID has been rejected
>- Remove the References
>- Both populated and unpopulated entries can be rejected
>- Merging entries can also result in rejected CVE Entries

I wasn't able to find more concrete or up to date information on _how_ to reject the CVE outside of that ppt, so it could be helpful to have someone update it to include this too 😄

2022-03-10 20:17 UTC, taladrane commented
thank you @anthnysingleton! I've made the change. I was following the section outlined [here](https://cve.mitre.org/cve/cna/CNA_Processes.pptx) (on the CNA processes section of the [Resources](https://www.cve.org/ResourcesSupport/Resources)) tab that said the following on slide 39:

> Rejection Process:
> Update the Description saying that the CVE ID has been rejected
> Remove the References
> Both populated and unpopulated entries can be rejected
> Merging entries can also result in rejected CVE Entries

I wasn't able to find more concrete or up to date information on how to reject the CVE outside of that ppt, so it could be helpful to have someone update it to include this too 😄

2022-03-10 20:20 UTC, cve-team requested changes
Auto validation errors:

2022-03-10 20:20 UTC, cve-team commented on 2022/24xxx/CVE-2022-24727.json
>      "CVE_data_meta": {
{} is not allowed for {'vendor': {'vendor_data': [{'product': {'product_data': [{'product_name': 'weblate', 'version': {'version_data': [{'version_value': '< 4.11.1'}]}}]}, 'vendor_name': 'WeblateOrg'}]}}

2022-03-10 20:20 UTC, cve-team commented on 2022/24xxx/CVE-2022-24727.json
>      "CVE_data_meta": {
{} is not allowed for {'problemtype_data': [{'description': [{'lang': 'eng', 'value': "CWE-77: Improper Neutralization of Special Elements used in a Command ('Command Injection')"}]}]}

2022-03-10 20:20 UTC, cve-team commented on 2022/24xxx/CVE-2022-24727.json
>      "CVE_data_meta": {
{} is not allowed for {'reference_data': []}

2022-03-10 20:45 UTC, cve-team requested changes
Auto validation errors:

2022-03-10 20:45 UTC, cve-team commented on 2022/24xxx/CVE-2022-24727.json
>      "CVE_data_meta": {
{} is not allowed for {'vendor': {'vendor_data': [{'product': {'product_data': [{'product_name': 'weblate', 'version': {'version_data': [{'version_value': '< 4.11.1'}]}}]}, 'vendor_name': 'WeblateOrg'}]}}

2022-03-10 20:45 UTC, cve-team commented on 2022/24xxx/CVE-2022-24727.json
>      "CVE_data_meta": {
{} is not allowed for {'problemtype_data': [{'description': [{'lang': 'eng', 'value': "CWE-77: Improper Neutralization of Special Elements used in a Command ('Command Injection')"}]}]}

2022-03-10 20:45 UTC, cve-team commented on 2022/24xxx/CVE-2022-24727.json
>      "CVE_data_meta": {
{} is not allowed for {'reference_data': []}

2022-03-10 20:56 UTC, anthnysingleton commented
@taladrane I think you want to remove those objects from the CVE Record. Your CVE Record should look like this:

```
{
    "CVE_data_meta": {
        "ASSIGNER": "security-advisories@github.com",
        "ID": "CVE-2022-24727",
        "STATE": "REJECT"
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
        "description_data": [
            {
                "lang": "eng",
                "value": "** REJECT ** DO NOT USE THIS CANDIDATE NUMBER. ConsultIDs: CVE-2022-23915. Reason: This candidate is a reservation duplicate of CVE-2022-23915. Notes: All CVE users should reference CVE-2022-23915 instead of this candidate. All references and descriptions in this candidate have been removed to prevent accidental usage."
            }
        ]
    }
}
```

2022-03-14 14:53 UTC, anthnysingleton commented
I have gone ahead and manually pulled this request in on our end. You should see the record updated in the next few hours.

2022-03-14 14:53 UTC, closed without merging

2022-03-14 15:06 UTC, taladrane commented
thank you @anthnysingleton! 🙌 sorry for the delay in handling on my end, I had just gotten on to handle this and saw that you did, much appreciated ❤️