Cna/divd/divd 2021 00029
CVEProject/cvelist pull request #4878
Opened 2022-03-12 08:24 UTC by MrSeccubus

2022-03-12 08:25 UTC, cve-team requested changes
Auto validation errors:

2022-03-12 08:25 UTC, cve-team commented on 2022/24xxx/CVE-2022-24387.json
>  {
{} is not allowed for {'vendor': {'vendor_data': [{'product': {'product_data': [{'product_name': 'SmarterTrack', 'version': {'version_data': [{'version_affected': '<=', 'version_name': '100.0.8019.x', 'version_value': 'Build 8075'}]}}]}, 'vendor_name': 'SmarterTools'}]}}

2022-03-12 08:25 UTC, cve-team commented on 2022/24xxx/CVE-2022-24387.json
>  {
{} is not allowed for {'problemtype_data': [{'description': [{'lang': 'eng', 'value': 'CWE-434 Unrestricted Upload of File with Dangerous Type'}]}]}

2022-03-12 08:25 UTC, cve-team commented on 2022/24xxx/CVE-2022-24387.json
>  {
{} is not allowed for {'reference_data': [{'name': 'https://csirt.divd.nl/DIVD-2021-00029', 'refsource': 'CONFIRM', 'url': 'https://csirt.divd.nl/DIVD-2021-00029'}, {'name': 'https://csrit.divd.nl/CVE-2022-24387', 'refsource': 'CONFIRM', 'url': 'https://csrit.divd.nl/CVE-2022-24387'}]}

2022-03-14 08:45 UTC, cve-team requested changes
Auto validation errors:

2022-03-14 08:45 UTC, cve-team commented on 2022/24xxx/CVE-2022-24387.json
>  {
{} is not allowed for {'vendor': {'vendor_data': [{'product': {'product_data': [{'product_name': 'SmarterTrack', 'version': {'version_data': [{'version_affected': '<=', 'version_name': '100.0.8019.x', 'version_value': 'Build 8075'}]}}]}, 'vendor_name': 'SmarterTools'}]}}

2022-03-14 08:45 UTC, cve-team commented on 2022/24xxx/CVE-2022-24387.json
>  {
{} is not allowed for {'problemtype_data': [{'description': [{'lang': 'eng', 'value': 'CWE-434 Unrestricted Upload of File with Dangerous Type'}]}]}

2022-03-14 08:45 UTC, cve-team commented on 2022/24xxx/CVE-2022-24387.json
>  {
{} is not allowed for {'reference_data': [{'name': 'https://csirt.divd.nl/DIVD-2021-00029', 'refsource': 'CONFIRM', 'url': 'https://csirt.divd.nl/DIVD-2021-00029'}, {'name': 'https://csrit.divd.nl/CVE-2022-24387', 'refsource': 'CONFIRM', 'url': 'https://csrit.divd.nl/CVE-2022-24387'}]}

2022-03-14 08:49 UTC, MrSeccubus commented
@cve-team I generated the JSON using Vulnogram and it validates there. Could you give me a pointer as to what is wrong?
The errors only occur on this particular record, not on any others.

HELP!

2022-03-14 08:55 UTC, cve-team requested changes
Auto validation errors:

2022-03-14 08:55 UTC, cve-team commented on 2022/24xxx/CVE-2022-24387.json
>  {
{} is not allowed for {'vendor': {'vendor_data': [{'product': {'product_data': [{'product_name': 'SmarterTrack', 'version': {'version_data': [{'version_affected': '<=', 'version_name': '100.0.8019.x', 'version_value': 'Build 8075'}]}}]}, 'vendor_name': 'SmarterTools'}]}}

2022-03-14 08:55 UTC, cve-team commented on 2022/24xxx/CVE-2022-24387.json
>  {
{} is not allowed for {'problemtype_data': [{'description': [{'lang': 'eng', 'value': 'CWE-434 Unrestricted Upload of File with Dangerous Type'}]}]}

2022-03-14 08:55 UTC, cve-team commented on 2022/24xxx/CVE-2022-24387.json
>  {
{} is not allowed for {'reference_data': [{'name': 'https://csirt.divd.nl/DIVD-2021-00029', 'refsource': 'CONFIRM', 'url': 'https://csirt.divd.nl/DIVD-2021-00029'}, {'name': 'https://csrit.divd.nl/CVE-2022-24387', 'refsource': 'CONFIRM', 'url': 'https://csrit.divd.nl/CVE-2022-24387'}]}

2022-03-14 12:16 UTC, merged

2022-03-14 12:18 UTC, MrSeccubus commented
Found the problem in the end. State was still set to "RESERVED" even tough we meant to publish.

it would be great if the error message was a bit clearer, e.g. :
```
For a "RESERVED" record, {} is not allowed for {'reference_data': [{'name': 'https://csirt.divd.nl/DIVD-2021-00029', 'refsource': 'CONFIRM', 'url': 'https://csirt.divd.nl/DIVD-2021-00029'}, {'name': 'https://csrit.divd.nl/CVE-2022-24387', 'refsource': 'CONFIRM', 'url': 'https://csrit.divd.nl/CVE-2022-24387'}]}
```

Is the validation tool on GitHub too, I'm happy to make a PR for this.