CVE-2022-25620
CVEProject/cvelist pull request #4981
Opened 2022-03-21 08:19 UTC by ulkuderner

CVE-2022-25620.json

2022-03-21 08:20 UTC, cve-team commented
ulkuderner is not recognized currently as an account participating in the Git Pilot. To ensure timely processing of your pull request, please contact the CVE Team using either the CVE Request web form (https://cveform.mitre.org/) or an email (cve@mitre.org) and confirm your identity.

2022-03-28 18:15 UTC, cve-team requested changes
Auto validation errors:

2022-03-28 18:15 UTC, cve-team commented on 2022/25xxx/CVE-2022-25620.json
>  {
An exception of type JSONDecodeError occurred. Arguments:

2022-03-28 18:15 UTC, cve-team commented on 2022/25xxx/CVE-2022-25620.json
>  {
('Invalid control character at: line 47 column 73 (char 1518)',)

2022-03-28 18:20 UTC, anthnysingleton commented
Hello @ulkuderner,

Once the errors in the file have been addressed we can proceed with publishing the information to the main list.

Thanks,
CVE Content Team

2022-03-30 14:45 UTC, cve-team requested changes
Auto validation errors:

2022-03-30 14:45 UTC, cve-team commented on 2022/25xxx/CVE-2022-25620.json
>  {
An exception of type JSONDecodeError occurred. Arguments:

2022-03-30 14:45 UTC, cve-team commented on 2022/25xxx/CVE-2022-25620.json
>  {
('Invalid control character at: line 47 column 73 (char 1518)',)

2022-03-30 14:50 UTC, cve-team requested changes
Auto validation errors:

2022-03-30 14:50 UTC, cve-team commented on 2022/25xxx/CVE-2022-25620.json
>  {
MISC or CONFIRM, but name != url for reference.

2022-03-30 14:55 UTC, merged