Cna/schnedier electric/20220329
CVEProject/cvelist pull request #5058
Opened 2022-03-28 16:37 UTC by Pazesm

2022-03-28 16:40 UTC, cve-team requested changes
Auto validation errors:

2022-03-28 16:40 UTC, cve-team commented on 2022/0xxx/CVE-2022-0715.json
>      "references": {
An exception of type JSONDecodeError occurred. Arguments:

2022-03-28 16:40 UTC, cve-team commented on 2022/0xxx/CVE-2022-0715.json
>      "references": {
('Expecting property name enclosed in double quotes: line 93 column 1 (char 4679)',)

2022-03-28 16:40 UTC, cve-team commented on 2022/22xxx/CVE-2022-22805.json
>      "references": {
An exception of type JSONDecodeError occurred. Arguments:

2022-03-28 16:40 UTC, cve-team commented on 2022/22xxx/CVE-2022-22805.json
>      "references": {
('Expecting property name enclosed in double quotes: line 71 column 1 (char 2881)',)

2022-03-28 16:40 UTC, cve-team commented on 2022/22xxx/CVE-2022-22806.json
>      "references": {
An exception of type JSONDecodeError occurred. Arguments:

2022-03-28 16:40 UTC, cve-team commented on 2022/22xxx/CVE-2022-22806.json
>      "references": {
('Expecting property name enclosed in double quotes: line 71 column 1 (char 2820)',)

2022-04-01 13:12 UTC, anthnysingleton commented
Hello @Pazesm,

Please resolve the validation errors so the request can be processed.

Thanks,
CVE Content Team

2022-04-13 15:44 UTC, Pazesm commented
Closing out as duplicate : https://github.com/CVEProject/cvelist/pull/5270

2022-04-13 15:44 UTC, closed without merging