This is not a vulnerability and was assigned against CNA guidelines
CVEProject/cvelist pull request #5067
Opened 2022-03-29 11:24 UTC by iamamoose

For commentary see https://github.com/openssl/openssl/issues/16873

2022-03-29 11:25 UTC, cve-team requested changes
Auto validation errors:

2022-03-29 11:25 UTC, cve-team commented on 2021/43xxx/CVE-2021-43085.json
>      "CVE_data_meta": {
CNA(s) of user (apache|openssl) do not match owning CNA.

2022-03-29 11:26 UTC, iamamoose commented on 2021/43xxx/CVE-2021-43085.json
>      "CVE_data_meta": {
Please have owning CNA reassign this CVE to OpenSSL CNA due to breach of CNA guidelines.

2022-03-30 15:16 UTC, anthnysingleton commented
Hello @iamamoose,

We have resolved the issue on our end [here](https://github.com/CVEProject/cvelist/blob/acbb5be766e78210bee16c711ae74981f213cd69/2021/43xxx/CVE-2021-43085.json) and the CNA Coordination Team will be reaching out to you shortly. 

Thanks,
CVE Content Team

2022-03-30 15:16 UTC, closed without merging