ZDI assigns the following CVEs:
CVEProject/cvelist pull request #516
Opened 2021-01-14 19:28 UTC by zdi-team

M 2020/27xxx/CVE-2020-27858.json
 M 2020/27xxx/CVE-2020-27859.json

2021-01-14 19:30 UTC, cve-team requested changes
Auto validation errors:

2021-01-14 19:30 UTC, cve-team commented on 2020/27xxx/CVE-2020-27858.json
>  {
CNA(s) of user (zdi) do not match owning CNA.

2021-01-14 19:30 UTC, cve-team commented on 2020/27xxx/CVE-2020-27859.json
>  {
CNA(s) of user (zdi) do not match owning CNA.

2021-01-20 17:35 UTC, zdi-team commented on 2020/27xxx/CVE-2020-27858.json
>  {
We don't know how to remedy this. Our username is zdi-team, which we've used before, and we are the "CNA of last resort" for vulnerabilities that come through the ZDI program as listed here: https://cve.mitre.org/cve/request_id.html#cna_participants

2021-01-20 19:09 UTC, cve-team approved these changes

2021-01-20 19:35 UTC, merged