Add CVE-2022-24825 for GHSA-gcj7-j438-hjj2
CVEProject/cvelist pull request #5213
Opened 2022-04-08 18:47 UTC by CallmeMari

Add CVE-2022-24825 for GHSA-gcj7-j438-hjj2

2022-04-08 18:50 UTC, cve-team requested changes
Auto validation errors:

2022-04-08 18:50 UTC, cve-team commented on 2022/24xxx/CVE-2022-24825.json
>  {
'github.com/stripe/smokescreen' does not match '^(ftp|http)s?://\\S+$'

2022-04-11 17:53 UTC, anthnysingleton commented on 2022/24xxx/CVE-2022-24825.json
> +                "name": "github.com/stripe/smokescreen",
Hey @CallmeMari,

Looks like the "name" and "url" attributes both are missing  "https://". Once that is fixed the process will continue and merge the PR. 

Thanks,
CVE Content Team

2022-04-19 19:45 UTC, CallmeMari commented on 2022/24xxx/CVE-2022-24825.json
> +                "name": "github.com/stripe/smokescreen",
Thank you for catching this, it has been fixed.

2022-04-19 19:45 UTC, merged