CNA/Loigtech - CVE-2022-0915
CVEProject/cvelist pull request #5251
Opened 2022-04-11 21:22 UTC by nhamzi

2022-04-11 21:25 UTC, cve-team commented
nhamzi is not recognized currently as an account participating in the Git Pilot. To ensure timely processing of your pull request, please contact the CVE Team using either the CVE Request web form (https://cveform.mitre.org/) or an email (cve@mitre.org) and confirm your identity.

2022-04-12 13:25 UTC, cve-team requested changes
Auto validation errors:

2022-04-12 13:25 UTC, cve-team commented on 2022/0xxx/CVE-2022-0915.json
>  {
Invalid JSON file (invalid state)

2022-04-12 13:49 UTC, anthnysingleton commented on 2022/0xxx/CVE-2022-0915.json
>  {
Hello @nhamzi,

The state should be "PUBLIC" and not "REVIEW"

2022-04-12 13:49 UTC, anthnysingleton commented on 2022/0xxx/CVE-2022-0915.json
>  {
Hello @nhamzi,

The state should be "PUBLIC" and not "REVIEW"

2022-04-12 18:35 UTC, merged