Add CVE-2022-24897 for GHSA-cvx5-m8vg-vxgc
CVEProject/cvelist pull request #5500
Opened 2022-04-28 20:03 UTC by shelbyc

Add CVE-2022-24897 for GHSA-cvx5-m8vg-vxgc

2022-04-28 20:05 UTC, cve-team requested changes
Auto validation errors:

2022-04-28 20:05 UTC, cve-team commented on 2022/24xxx/CVE-2022-24897.json
>  {
' https://jira.xwiki.org/browse/XWIKI-5168' does not match '^(ftp|http)s?://\\S+$'

2022-04-29 14:03 UTC, anthnysingleton commented on 2022/24xxx/CVE-2022-24897.json
> +            {
Hey @shelbyc looks like there is a leading white space in this URL object. Fixing that will unblock processing.

2022-05-02 21:51 UTC, anthnysingleton commented
Hello @shelbyc,

This PR has been in a blocked state for a few days. I have gone ahead and pulled the file in a manually process the CVE Record. 

https://www.cve.org/CVERecord?id=CVE-2022-24897

I will not close this PR. If you need to make any additional changes to this record please feel free to open a new PR.

Thanks,
CVE Content Team

2022-05-02 21:51 UTC, closed without merging

2022-05-03 20:29 UTC, shelbyc commented on 2022/24xxx/CVE-2022-24897.json
> +            {
Thank you for your help!