CVE records for May 5th
CVEProject/cvelist pull request #5613
Opened 2022-05-05 20:53 UTC by monicamurray

2022-05-05 20:55 UTC, cve-team requested changes
Auto validation errors:

2022-05-05 20:55 UTC, cve-team commented on 2021/27xxx/CVE-2021-27759.json
>  {
An exception of type JSONDecodeError occurred. Arguments:

2022-05-05 20:55 UTC, cve-team commented on 2021/27xxx/CVE-2021-27759.json
>  {
('Invalid control character at: line 5 column 32 (char 144)',)

2022-05-05 21:08 UTC, monicamurray commented on 2021/27xxx/CVE-2021-27759.json
>  {
I modified that line and am trying a new git push...

2022-05-05 21:10 UTC, cve-team requested changes
Auto validation errors:

2022-05-05 21:10 UTC, cve-team commented on 2021/27xxx/CVE-2021-27759.json
>  {
An exception of type JSONDecodeError occurred. Arguments:

2022-05-05 21:10 UTC, cve-team commented on 2021/27xxx/CVE-2021-27759.json
>  {
('Expecting value: line 50 column 33 (char 1718)',)

2022-05-05 21:35 UTC, cve-team requested changes
Auto validation errors:

2022-05-05 21:35 UTC, cve-team commented on 2021/27xxx/CVE-2021-27759.json
>  {
An exception of type JSONDecodeError occurred. Arguments:

2022-05-05 21:35 UTC, cve-team commented on 2021/27xxx/CVE-2021-27759.json
>  {
('Expecting value: line 55 column 38 (char 1918)',)

2022-05-05 22:03 UTC, monicamurray commented on 2021/27xxx/CVE-2021-27759.json
>  {
corrected line 55

2022-05-06 02:40 UTC, anthnysingleton commented on 2021/27xxx/CVE-2021-27759.json
>  {
Looks like there is some weird char at the beginning of this file before the { bracket.

2022-05-06 02:42 UTC, anthnysingleton commented on 2021/27xxx/CVE-2021-27759.json
> +            "confidentialityImpact": “LOW”,
The qoutes for the values of confidentialityImpact, privilegesRequired, and userInteraction are not accepted. This usually happens from a copy/paste. Just remove quotes and reapply quotes in your editor.

2022-05-06 14:30 UTC, monicamurray commented
I see a message showing cve-team requested changes, but I do not see any comments about the change needed.  Please post any additional errors found.

2022-05-06 17:09 UTC, anthnysingleton commented
I posted two comments last night. Once you resolve the issues in [2021/27xxx/CVE-2021-27759.json](https://github.com/CVEProject/cvelist/pull/5613/files/a64422dbf5b96f373d48ba9f02d2219ba6cfd9d5#diff-be82be3abe8d51b38ae5775ceb78ec13f4c116605491afd735e1894a95c66cf3) then PR will continue to be processed. We are close to getting your first PR accepted =]

2022-05-06 17:38 UTC, monicamurray commented
ok, I think I fixed the errors.  Fingers crossed!

2022-05-06 18:10 UTC, merged