update two CVEs
CVEProject/cvelist pull request #5632
Opened 2022-05-06 13:29 UTC by CERT-VDE

2022-05-06 13:30 UTC, cve-team requested changes
Auto validation errors:

2022-05-06 13:30 UTC, cve-team commented on 2021/46xxx/CVE-2021-46380.json
>  {
{} is not allowed for {'vendor': {'vendor_data': [{'product': {'product_data': [{'version': {'version_data': [{}]}}]}}]}}

2022-05-06 13:30 UTC, cve-team commented on 2021/46xxx/CVE-2021-46380.json
>  {
{} is not allowed for {'problemtype_data': [{'description': [{'lang': 'eng'}]}]}

2022-05-06 13:30 UTC, cve-team commented on 2021/46xxx/CVE-2021-46380.json
>  {
{} is not allowed for {'reference_data': [{'refsource': 'CONFIRM'}]}

2022-05-06 13:35 UTC, cve-team requested changes
Auto validation errors:

2022-05-06 13:35 UTC, cve-team commented on 2021/46xxx/CVE-2021-46380.json
>  {
An exception of type JSONDecodeError occurred. Arguments:

2022-05-06 13:35 UTC, cve-team commented on 2021/46xxx/CVE-2021-46380.json
>  {
('Expecting property name enclosed in double quotes: line 18 column 1 (char 476)',)

2022-05-06 13:40 UTC, cve-team requested changes
Auto validation errors:

2022-05-06 13:40 UTC, cve-team commented on 2019/12xxx/CVE-2019-12254.json
>  {
CNA(s) of user (CERTVDE) do not match owning CNA.

2022-05-06 13:40 UTC, cve-team commented on 2021/46xxx/CVE-2021-46380.json
>  {
CNA(s) of user (CERTVDE) do not match owning CNA.

2022-05-06 13:40 UTC, CERT-VDE commented on 2019/12xxx/CVE-2019-12254.json
>  {
That's a pre-CNA CVE of cert@vde

2022-05-06 13:41 UTC, CERT-VDE commented on 2021/46xxx/CVE-2021-46380.json
>  {
See CVE Request 1242802

2022-05-06 17:30 UTC, merged

2022-05-06 17:30 UTC, anthnysingleton commented
Hello @CERT-VDE,

I have gone in and switched these two records over to your Org. Thank you for being patient. 

CVE Content Team

2022-05-09 05:08 UTC, CERT-VDE commented
> I have gone in and switched these two records over to your Org. Thank you for being patient.

@anthnysingleton 
Thank you Anthony!

CERT@VDE /jochen