Add the reporter blogpost for CVE-2022-27909
CVEProject/cvelist pull request #5650
Opened 2022-05-09 18:20 UTC by zero-24

2022-05-09 18:25 UTC, cve-team requested changes
Auto validation errors:

2022-05-09 18:25 UTC, cve-team commented on 2022/27xxx/CVE-2022-27909.json
>                  "url": "https://www.jdownloads.com/index.php/downloads/download/57-jdownloads-3-9.html",
'https://hackerhood.redhotcyber.com/cve-2022-27909-jdownloads/ ' does not match '^(ftp|http)s?://\\S+$'

2022-05-09 18:27 UTC, zero-24 commented on 2022/27xxx/CVE-2022-27909.json
>                  "url": "https://www.jdownloads.com/index.php/downloads/download/57-jdownloads-3-9.html",
@cve-team can you please double check that regex? The URL looks valid to me?

2022-05-10 14:00 UTC, anthnysingleton commented on 2022/27xxx/CVE-2022-27909.json
>                  "url": "https://www.jdownloads.com/index.php/downloads/download/57-jdownloads-3-9.html",
The issue is with the trailing white space at the end of the string. Can you remove it with an update?

2022-05-10 14:08 UTC, zero-24 commented on 2022/27xxx/CVE-2022-27909.json
>                  "url": "https://www.jdownloads.com/index.php/downloads/download/57-jdownloads-3-9.html",
I'm sorry it has been fixed

2022-05-10 14:10 UTC, merged