QSA-22-18
CVEProject/cvelist pull request #5886
Opened 2022-05-26 04:12 UTC by stanleyshuang

CVE-2021-34360

2022-05-26 04:15 UTC, cve-team requested changes
Auto validation errors:

2022-05-26 04:15 UTC, cve-team commented on 2021/34xxx/CVE-2021-34360.json
>  {
'data_type' is a required property

2022-05-26 04:15 UTC, cve-team commented on 2021/34xxx/CVE-2021-34360.json
>  {
'data_format' is a required property

2022-05-26 04:15 UTC, cve-team commented on 2021/34xxx/CVE-2021-34360.json
>  {
'data_version' is a required property

2022-05-26 04:15 UTC, cve-team commented on 2021/34xxx/CVE-2021-34360.json
>  {
'CVE_data_meta' is a required property

2022-05-26 04:15 UTC, cve-team commented on 2021/34xxx/CVE-2021-34360.json
>  {
'affects' is a required property

2022-05-26 04:15 UTC, cve-team commented on 2021/34xxx/CVE-2021-34360.json
>  {
'problemtype' is a required property

2022-05-26 04:15 UTC, cve-team commented on 2021/34xxx/CVE-2021-34360.json
>  {
'references' is a required property

2022-05-26 04:15 UTC, cve-team commented on 2021/34xxx/CVE-2021-34360.json
>  {
'description' is a required property

2022-05-26 13:38 UTC, anthnysingleton commented
Hello @stanleyshuang ,

Please resolve the merge conflict. Once resolved the automated process will continue.

Thanks,
CVE Content Team

2022-05-31 14:15 UTC, anthnysingleton commented
Hello @stanleyshuang,

The CVE Github Pilot does not accept JSON v5. You can only submit JSON v4 through this endpoint. 

Closing PR.

Thanks,
CVE Content Team

2022-05-31 14:15 UTC, closed without merging