Update CVE-2022-29244.json
CVEProject/cvelist pull request #5965
Opened 2022-06-02 15:45 UTC by taladrane

2022-06-02 15:50 UTC, cve-team requested changes
Auto validation errors:

2022-06-02 15:50 UTC, cve-team commented on 2022/29xxx/CVE-2022-29244.json
>  {
CNA(s) of user (GitHub_P) do not match owning CNA.

2022-06-02 15:59 UTC, taladrane commented on 2022/29xxx/CVE-2022-29244.json
>  {
this is a part of the GitHub_M CNA, not GitHub_P - https://www.cve.org/PartnerInformation/ListofPartners/partner/GitHub_M

2022-06-02 16:40 UTC, cve-team requested changes
Auto validation errors:

2022-06-02 16:40 UTC, cve-team commented on 2022/29xxx/CVE-2022-29244.json
>  {
CNA(s) of user (GitHub_P) do not match owning CNA.

2022-06-03 13:37 UTC, taladrane commented on 2022/29xxx/CVE-2022-29244.json
>  {
@anthnysingleton would you mind taking a look at this and letting me know if I need to change anything? it's a critical vulnerability in the npm cli so I'd love to get this populated ASAP 🙏

2022-06-13 13:29 UTC, anthnysingleton commented on 2022/29xxx/CVE-2022-29244.json
>  {
Hello @taladrane,

Will you be submitting for both GitHub_P and GitHub_M? I have just have to make the adjustment on my end to permission you correctly.

Thanks,
CVE Content Team

2022-06-13 13:40 UTC, merged

2022-06-28 18:59 UTC, taladrane commented on 2022/29xxx/CVE-2022-29244.json
>  {
Hi @anthnysingleton - no I will not be submitting for both, I will just be submitting for GitHub_M. Thank you for handling this!