Update CVE-2022-21504
CVEProject/cvelist pull request #6062
Opened 2022-06-10 22:11 UTC by bsitu

On branch cna/Oracle/CVE-2022-21504
 Changes to be committed:
	modified:   2022/21xxx/CVE-2022-21504.json

2022-06-10 22:15 UTC, cve-team requested changes
Auto validation errors:

2022-06-10 22:15 UTC, cve-team commented on 2022/21xxx/CVE-2022-21504.json
> +
An exception of type JSONDecodeError occurred. Arguments:

2022-06-10 22:15 UTC, cve-team commented on 2022/21xxx/CVE-2022-21504.json
> +
('Expecting property name enclosed in double quotes: line 34 column 25 (char 1180)',)

2022-06-10 22:20 UTC, cve-team requested changes
Auto validation errors:

2022-06-10 22:20 UTC, cve-team commented on 2022/21xxx/CVE-2022-21504.json
> +
An exception of type JSONDecodeError occurred. Arguments:

2022-06-10 22:20 UTC, cve-team commented on 2022/21xxx/CVE-2022-21504.json
> +
('Expecting value: line 33 column 25 (char 1171)',)

2022-06-10 22:25 UTC, cve-team requested changes
Auto validation errors:

2022-06-10 22:25 UTC, cve-team commented on 2022/21xxx/CVE-2022-21504.json
> +
An exception of type JSONDecodeError occurred. Arguments:

2022-06-10 22:25 UTC, cve-team commented on 2022/21xxx/CVE-2022-21504.json
> +
('Expecting value: line 32 column 25 (char 1160)',)

2022-06-14 17:35 UTC, cve-team requested changes
Auto validation errors:

2022-06-14 17:35 UTC, cve-team commented on 2022/21xxx/CVE-2022-21504.json
> +
An exception of type JSONDecodeError occurred. Arguments:

2022-06-14 17:35 UTC, cve-team commented on 2022/21xxx/CVE-2022-21504.json
> +
('Expecting property name enclosed in double quotes: line 72 column 13 (char 3110)',)

2022-06-14 17:39 UTC, bsitu commented
The last comment shown above is "This branch has no conflicts with the base branch". Is there something else preventing the merge? Thanks.

2022-06-14 17:50 UTC, merged

2022-06-14 17:51 UTC, bsitu commented
Thank you!