ZDI assigns the following CVEs:
CVEProject/cvelist pull request #6652
Opened 2022-07-25 16:42 UTC by zdi-team

M  2022/28xxx/CVE-2022-28668.json
M  2022/28xxx/CVE-2022-28684.json
M  2022/2xxx/CVE-2022-2272.json
M  2022/34xxx/CVE-2022-34871.json
M  2022/34xxx/CVE-2022-34872.json
M  2022/35xxx/CVE-2022-35864.json
M  2022/35xxx/CVE-2022-35865.json
M  2022/35xxx/CVE-2022-35866.json
M  2022/35xxx/CVE-2022-35867.json

2022-07-25 16:45 UTC, cve-team requested changes
Auto validation errors:

2022-07-25 16:45 UTC, cve-team commented on 2022/34xxx/CVE-2022-34871.json
>  {
'https://docs.centreon.com/docs/21.10/releases/centreon-core/\r\n\r\nhttps://github.com/centreon/centreon/blob/master/SECURITY_ACK.md#-2022-' does not match '^(ftp|http)s?://\\S+$'

2022-07-25 16:45 UTC, cve-team commented on 2022/34xxx/CVE-2022-34872.json
>  {
'https://docs.centreon.com/docs/21.10/releases/centreon-core/\r\n\r\nhttps://github.com/centreon/centreon/blob/master/SECURITY_ACK.md#-2022-' does not match '^(ftp|http)s?://\\S+$'

2022-07-28 20:19 UTC, anthnysingleton requested changes
Hello @zdi-team,

Two of your files have references that have two urls in one string. Once this is resolved we can continue processing this PR to the main list. 

Thanks,
CVE Content Team

2022-07-28 20:19 UTC, anthnysingleton commented on 2022/34xxx/CVE-2022-34872.json
> +        "url": "https://docs.centreon.com/docs/21.10/releases/centreon-core/\r\n\r\nhttps://github.com/centreon/centreon/blob/master/SECURITY_ACK.md#-2022-"
Looks like a bug in automation here. Two urls listed in this string.

2022-07-28 20:19 UTC, anthnysingleton commented on 2022/34xxx/CVE-2022-34871.json
> +        "url": "https://docs.centreon.com/docs/21.10/releases/centreon-core/\r\n\r\nhttps://github.com/centreon/centreon/blob/master/SECURITY_ACK.md#-2022-"
Looks like a bug in automation here. Two urls listed in this string.

2022-07-29 18:54 UTC, kernelsmith commented on 2022/34xxx/CVE-2022-34871.json
> +        "url": "https://docs.centreon.com/docs/21.10/releases/centreon-core/\r\n\r\nhttps://github.com/centreon/centreon/blob/master/SECURITY_ACK.md#-2022-"
We get those URLs from the vendor, then a human enters them in. I must need to update our JSON schemas because they didn't fail validation before they went to you. Apologies. We'll fix

2022-08-03 15:18 UTC, kernelsmith commented on 2022/34xxx/CVE-2022-34872.json
> +        "url": "https://docs.centreon.com/docs/21.10/releases/centreon-core/\r\n\r\nhttps://github.com/centreon/centreon/blob/master/SECURITY_ACK.md#-2022-"
The vendor sends us that and a human puts it in. What baffles me is, why did my JSON schema validate, but yours caught it. I bet our schema isn't caught up to the latest. 

Thanks. Updated.

2022-08-03 15:18 UTC, kernelsmith commented on 2022/34xxx/CVE-2022-34871.json
> +        "url": "https://docs.centreon.com/docs/21.10/releases/centreon-core/\r\n\r\nhttps://github.com/centreon/centreon/blob/master/SECURITY_ACK.md#-2022-"
updated

2022-08-03 15:22 UTC, merged