add more tmux details
CVEProject/cvelist pull request #67
Opened 2020-11-10 02:52 UTC by setharnold

A fellow cve consumer from netbsd has asked for some more details in the description and another url in the references. Most of the url noise is just vulnogram reordering json fields.

2020-11-16 23:18 UTC, cristina479 commented
@setharnold Please resolve the conflicts so that we can publish the changes to CVE-2020-27347.

2020-11-17 01:49 UTC, setharnold commented
Hello @cristina479 , I believe I've done so. Thanks

2020-11-17 01:50 UTC, cve-team requested changes
Auto validation errors:

2020-11-17 01:50 UTC, cve-team commented on 2020/27xxx/CVE-2020-27347.json
>          "description_data": [
An exception of type JSONDecodeError occurred. Arguments:

2020-11-17 01:50 UTC, cve-team commented on 2020/27xxx/CVE-2020-27347.json
>          "description_data": [
("Expecting ',' delimiter: line 120 column 17 (char 4288)",)

2020-11-17 18:35 UTC, merged