Add CVE-2021-43309
CVEProject/cvelist pull request #6782
Opened 2022-08-03 08:46 UTC by srmish-jfrog

2022-08-03 08:50 UTC, cve-team requested changes
Auto validation errors:

2022-08-03 08:50 UTC, cve-team commented on 2021/43xxx/CVE-2021-43309.json
>  {
'' does not match '^([a-zA-Z0-9_\\-\\.]+)@([a-zA-Z0-9_\\-\\.]+)\\.([a-zA-Z]{2,5})$'

2022-08-03 12:02 UTC, srmish-jfrog commented on 2021/43xxx/CVE-2021-43309.json
>  {
Fixed in new version

2022-08-22 18:12 UTC, anthnysingleton commented on 2021/43xxx/CVE-2021-43309.json
> +        "name": ""
Hello @srmish-jfrog ,

If the reference does not have a name/title then you do not need to include the attribute "name" in the file. Because it was left as an empty string it was sitting here without being processed. I went ahead and pulled it in internally and processed the JSON file.

2022-08-22 18:13 UTC, anthnysingleton reviewed
Reviewed and provided feedback. Processed JSON internally and will close this PR as it is no longer needed.

2022-08-22 18:13 UTC, closed without merging