Adding Cisco CVE-2022-20920
CVEProject/cvelist pull request #7515
Opened 2022-09-30 18:41 UTC by santosomar

2022-09-30 18:46 UTC, cve-team requested changes
Auto validation errors:

2022-09-30 18:46 UTC, cve-team commented on 2022/20xxx/CVE-2022-20920.json
> -{
An exception of type JSONDecodeError occurred. Arguments:

2022-09-30 18:46 UTC, cve-team commented on 2022/20xxx/CVE-2022-20920.json
> -{
('Expecting value: line 1 column 1 (char 0)',)

2022-10-07 15:43 UTC, anthnysingleton commented
Hello @santosomar,

A few of your submitted PRs are blocked due to errors in the JSON file. Can you take a look at the responses and submit a new commit? We are also getting requests in regards to why this entry is not in the main list yet.

Thanks,
Anthony
CVE Content Team

2022-10-10 20:45 UTC, merged