Qualcomm CVEs for October.
CVEProject/cvelist pull request #7638
Opened 2022-10-12 08:56 UTC by QC-CNA

2022-10-17 19:42 UTC, anthnysingleton requested changes
Hello @QC-CNA,

We have not been able to fully process your PR. There are 8 records that contain "version_value" strings that are too long. Can you please parse out your product version information into separate arrays? I have provided a high level structure in the review. 

Thanks,
CVE Content Team

2022-10-17 19:42 UTC, anthnysingleton commented on 2022/25xxx/CVE-2022-25666.json
> +                                 "version_value": "APQ8096AU, AQT1000, AR9380, CSR8811, IPQ4018, IPQ4019, IPQ4028, IPQ4029, IPQ5010, IPQ5018, IPQ5028, IPQ6010, IPQ6018, IPQ6028, IPQ8064, IPQ8065, IPQ
Your list of product versions is too long here exceeding 1300 chars. Please parse your product_data into multiple arrays with the version value not exceeding 1300 chars.

```
"product_data":[
     {
        "product_name": "Product 1",
        "version": {
             "version_data": [
                   {
                       "version_value": "affected/fixed versions for Product 1"
                   }
                ]
         }
     },
    {
        "product_name": "Product N",
        "version": {
             "version_data": [
                   {
                       "version_value": "affected/fixed versions for Product N"
                   }
                ]
         }
     }
]
```

2022-10-17 19:42 UTC, anthnysingleton commented on 2022/25xxx/CVE-2022-25687.json
> +                  "product_data": [
Your list of product versions is too long here exceeding 1300 chars. Please parse your product_data into multiple arrays with the version value not exceeding 1300 chars.

```
"product_data":[
     {
        "product_name": "Product 1",
        "version": {
             "version_data": [
                   {
                       "version_value": "affected/fixed versions for Product 1"
                   }
                ]
         }
     },
    {
        "product_name": "Product N",
        "version": {
             "version_data": [
                   {
                       "version_value": "affected/fixed versions for Product N"
                   }
                ]
         }
     }
]
```

2022-10-17 19:42 UTC, anthnysingleton commented on 2022/25xxx/CVE-2022-25718.json
> +                  "product_data": [
Your list of product versions is too long here exceeding 1300 chars. Please parse your product_data into multiple arrays with the version value not exceeding 1300 chars.

```
"product_data":[
     {
        "product_name": "Product 1",
        "version": {
             "version_data": [
                   {
                       "version_value": "affected/fixed versions for Product 1"
                   }
                ]
         }
     },
    {
        "product_name": "Product N",
        "version": {
             "version_data": [
                   {
                       "version_value": "affected/fixed versions for Product N"
                   }
                ]
         }
     }
]
```

2022-10-17 19:42 UTC, anthnysingleton commented on 2022/25xxx/CVE-2022-25719.json
> +                  "product_data": [
Your list of product versions is too long here exceeding 1300 chars. Please parse your product_data into multiple arrays with the version value not exceeding 1300 chars.

```
"product_data":[
     {
        "product_name": "Product 1",
        "version": {
             "version_data": [
                   {
                       "version_value": "affected/fixed versions for Product 1"
                   }
                ]
         }
     },
    {
        "product_name": "Product N",
        "version": {
             "version_data": [
                   {
                       "version_value": "affected/fixed versions for Product N"
                   }
                ]
         }
     }
]
```

2022-10-17 19:42 UTC, anthnysingleton commented on 2022/25xxx/CVE-2022-25720.json
> +                  "product_data": [
Your list of product versions is too long here exceeding 1300 chars. Please parse your product_data into multiple arrays with the version value not exceeding 1300 chars.

```
"product_data":[
     {
        "product_name": "Product 1",
        "version": {
             "version_data": [
                   {
                       "version_value": "affected/fixed versions for Product 1"
                   }
                ]
         }
     },
    {
        "product_name": "Product N",
        "version": {
             "version_data": [
                   {
                       "version_value": "affected/fixed versions for Product N"
                   }
                ]
         }
     }
]
```

2022-10-17 19:42 UTC, anthnysingleton commented on 2022/25xxx/CVE-2022-25736.json
> +                  "product_data": [
Your list of product versions is too long here exceeding 1300 chars. Please parse your product_data into multiple arrays with the version value not exceeding 1300 chars.

```
"product_data":[
     {
        "product_name": "Product 1",
        "version": {
             "version_data": [
                   {
                       "version_value": "affected/fixed versions for Product 1"
                   }
                ]
         }
     },
    {
        "product_name": "Product N",
        "version": {
             "version_data": [
                   {
                       "version_value": "affected/fixed versions for Product N"
                   }
                ]
         }
     }
]
```

2022-10-17 19:42 UTC, anthnysingleton commented on 2022/25xxx/CVE-2022-25748.json
> +                  "product_data": [
Your list of product versions is too long here exceeding 1300 chars. Please parse your product_data into multiple arrays with the version value not exceeding 1300 chars.

```
"product_data":[
     {
        "product_name": "Product 1",
        "version": {
             "version_data": [
                   {
                       "version_value": "affected/fixed versions for Product 1"
                   }
                ]
         }
     },
    {
        "product_name": "Product N",
        "version": {
             "version_data": [
                   {
                       "version_value": "affected/fixed versions for Product N"
                   }
                ]
         }
     }
]
```

2022-10-17 19:42 UTC, anthnysingleton commented on 2022/25xxx/CVE-2022-25749.json
> +                  "product_data": [
Your list of product versions is too long here exceeding 1300 chars. Please parse your product_data into multiple arrays with the version value not exceeding 1300 chars.

```
"product_data":[
     {
        "product_name": "Product 1",
        "version": {
             "version_data": [
                   {
                       "version_value": "affected/fixed versions for Product 1"
                   }
                ]
         }
     },
    {
        "product_name": "Product N",
        "version": {
             "version_data": [
                   {
                       "version_value": "affected/fixed versions for Product N"
                   }
                ]
         }
     }
]
```

2022-10-19 10:46 UTC, QC-CNA commented
Changes updated on this branch as per recommendation.

2022-10-19 10:46 UTC, merged

2022-10-19 10:49 UTC, QC-CNA commented
Hi Team,
Updated the CVE JSON files as per the recommendation. Please let us know if anything else is needed.


Padmalochan Panda
Qualcomm Product Security

From: anthnysingleton ***@***.***>
Sent: Tuesday, October 18, 2022 1:13 AM
To: CVEProject/cvelist ***@***.***>
Cc: security.cna ***@***.***>; Mention ***@***.***>
Subject: Re: [CVEProject/cvelist] Qualcomm CVEs for October. (PR #7638)


WARNING: This email originated from outside of Qualcomm. Please be wary of any links or attachments, and do not enable macros.

@anthnysingleton requested changes on this pull request.

Hello @QC-CNA<https://github.com/QC-CNA>,

We have not been able to fully process your PR. There are 8 records that contain "version_value" strings that are too long. Can you please parse out your product version information into separate arrays? I have provided a high level structure in the review.

Thanks,
CVE Content Team

________________________________

In 2022/25xxx/CVE-2022-25666.json<https://github.com/CVEProject/cvelist/pull/7638#discussion_r997439442>:

>              {

-                "lang": "eng",

-                "value": "** RESERVED ** This candidate has been reserved by an organization or individual that will use it when announcing a new security problem. When the candidate has been publicized, the details for this candidate will be provided."

+               "product": {

+                  "product_data": [

+                     {

+                        "product_name": "Snapdragon Auto, Snapdragon Compute, Snapdragon Consumer IOT, Snapdragon Industrial IOT, Snapdragon Mobile, Snapdragon Wearables, Snapdragon Wired Infrastructure and Networking",

+                        "version": {

+                           "version_data": [

+                              {

+                                 "version_value": "APQ8096AU, AQT1000, AR9380, CSR8811, IPQ4018, IPQ4019, IPQ4028, IPQ4029, IPQ5010, IPQ5018, IPQ5028, IPQ6010, IPQ6018, IPQ6028, IPQ8064, IPQ8065, IPQ8068, IPQ8070, IPQ8070A, IPQ8071A, IPQ8072A, IPQ8074A, IPQ8076, IPQ8076A, IPQ8078, IPQ8078A, IPQ8173, IPQ8174, MDM9150, MDM9650, MSM8996AU, PMP8074, QAM8295P, QCA4024, QCA6310, QCA6320, QCA6335, QCA6390, QCA6391, QCA6420, QCA6426, QCA6430, QCA6436, QCA6564, QCA6564A, QCA6564AU, QCA6574, QCA6574A, QCA6574AU, QCA6595AU, QCA6696, QCA7500, QCA8072, QCA8075, QCA8081, QCA8337, QCA9880, QCA9886, QCA9888, QCA9889, QCA9898, QCA9980, QCA9984, QCA9985, QCA9990, QCA9992, QCA9994, QCC5100, QCN5021, QCN5022, QCN5024, QCN5052, QCN5054, QCN5122, QCN5124, QCN5152, QCN5154, QCN5164, QCN6023, QCN6024, QCN6122, QCN6132, QCN9000, QCN9012, QCN9022, QCN9024, QCN9070, QCN9072, QCN9074, QCN9100, QCS410, QCS610, QCS8155, QSM8250, Qualcomm215, SA515M, SA6145P, SA6150P, SA6155, SA6155P, SA8145P, SA8150P, SA8155, SA8155P, SA8195P, SA8295P, SD 8 Gen1 5G, SD205, SD210, SD429, SD835, SD845, SD855, SD865 5G, SD870, SD888 5G, SDA429W, SDM429W, SDX55, SDX55M, SDXR2 5G, SW5100, SW5100P, WCD9335, WCD9340, WCD9341, WCD9370, WCD9380, WCD9385, WCN3610, WCN3620, WCN3660B, WCN3680B, WCN3950, WCN3980, WCN3988, WCN3990, WCN3998, WCN6850, WCN6851, WCN6855, WCN6856, WCN7850, WCN7851, WSA8810, WSA8815, WSA8830, WSA8835"

Your list of product versions is too long here exceeding 1300 chars. Please parse your product_data into multiple arrays with the version value not exceeding 1300 chars.

"product_data":[

     {

        "product_name": "Product 1",

        "version": {

             "version_data": [

                   {

                       "version_value": "affected/fixed versions for Product 1"

                   }

                ]

         }

     },

    {

        "product_name": "Product N",

        "version": {

             "version_data": [

                   {

                       "version_value": "affected/fixed versions for Product N"

                   }

                ]

         }

     }

]

________________________________

In 2022/25xxx/CVE-2022-25687.json<https://github.com/CVEProject/cvelist/pull/7638#discussion_r997440359>:

>              {

-                "lang": "eng",

-                "value": "** RESERVED ** This candidate has been reserved by an organization or individual that will use it when announcing a new security problem. When the candidate has been publicized, the details for this candidate will be provided."

+               "product": {

+                  "product_data": [

Your list of product versions is too long here exceeding 1300 chars. Please parse your product_data into multiple arrays with the version value not exceeding 1300 chars.

"product_data":[

     {

        "product_name": "Product 1",

        "version": {

             "version_data": [

                   {

                       "version_value": "affected/fixed versions for Product 1"

                   }

                ]

         }

     },

    {

        "product_name": "Product N",

        "version": {

             "version_data": [

                   {

                       "version_value": "affected/fixed versions for Product N"

                   }

                ]

         }

     }

]

________________________________

In 2022/25xxx/CVE-2022-25718.json<https://github.com/CVEProject/cvelist/pull/7638#discussion_r997440828>:

>              {

-                "lang": "eng",

-                "value": "** RESERVED ** This candidate has been reserved by an organization or individual that will use it when announcing a new security problem. When the candidate has been publicized, the details for this candidate will be provided."

+               "product": {

+                  "product_data": [

Your list of product versions is too long here exceeding 1300 chars. Please parse your product_data into multiple arrays with the version value not exceeding 1300 chars.

"product_data":[

     {

        "product_name": "Product 1",

        "version": {

             "version_data": [

                   {

                       "version_value": "affected/fixed versions for Product 1"

                   }

                ]

         }

     },

    {

        "product_name": "Product N",

        "version": {

             "version_data": [

                   {

                       "version_value": "affected/fixed versions for Product N"

                   }

                ]

         }

     }

]

________________________________

In 2022/25xxx/CVE-2022-25719.json<https://github.com/CVEProject/cvelist/pull/7638#discussion_r997441306>:

>              {

-                "lang": "eng",

-                "value": "** RESERVED ** This candidate has been reserved by an organization or individual that will use it when announcing a new security problem. When the candidate has been publicized, the details for this candidate will be provided."

+               "product": {

+                  "product_data": [

Your list of product versions is too long here exceeding 1300 chars. Please parse your product_data into multiple arrays with the version value not exceeding 1300 chars.

"product_data":[

     {

        "product_name": "Product 1",

        "version": {

             "version_data": [

                   {

                       "version_value": "affected/fixed versions for Product 1"

                   }

                ]

         }

     },

    {

        "product_name": "Product N",

        "version": {

             "version_data": [

                   {

                       "version_value": "affected/fixed versions for Product N"

                   }

                ]

         }

     }

]

________________________________

In 2022/25xxx/CVE-2022-25720.json<https://github.com/CVEProject/cvelist/pull/7638#discussion_r997441593>:

>              {

-                "lang": "eng",

-                "value": "** RESERVED ** This candidate has been reserved by an organization or individual that will use it when announcing a new security problem. When the candidate has been pu [...]