TR-CERT/CVE-2022-3792/20221219
CVEProject/cvelist pull request #8329
Opened 2022-12-19 12:49 UTC by TR-CERT

2022-12-19 12:50 UTC, cve-team requested changes
Auto validation errors:

2022-12-19 12:50 UTC, cve-team commented on 2022/3xxx/CVE-2022-3792.json
>  {
File name CVE ID and JSON CVE ID do not match.

2023-01-05 14:26 UTC, anthnysingleton reviewed
Hello @TR-CERT ,

This PR is held up because the reference object contains attributes called "name" that are set to empty strings. If you can update the file and remove those attributes we can then process the PR.

Thanks,
CVE Content Team

2023-01-05 14:26 UTC, anthnysingleton commented on 2022/3xxx/CVE-2022-3792.json
> +        "name": ""
If there is no name for the reference, please remove the empty attribute.

2023-01-05 14:26 UTC, anthnysingleton commented on 2022/3xxx/CVE-2022-3792.json
> +        "name": ""
If there is no name for the reference, please remove the empty attribute.

2023-01-05 14:26 UTC, anthnysingleton commented on 2022/3xxx/CVE-2022-3792.json
> +        "name": ""
If there is no name for the reference, please remove the empty attribute.

2023-01-10 13:45 UTC, merged