CVE 2022 0668 - JFrog
CVEProject/cvelist pull request #8437
Opened 2023-01-02 13:44 UTC by liavgutman

2023-01-05 14:18 UTC, anthnysingleton commented
Hello @liavgutman,

The cvelist CVE GitHub repo only accepts JSON V4 for submissions. You have opened a PR with JSON V5. 

Thanks,
CVE Content Team

2023-01-08 12:45 UTC, jamesjames1122 approved these changes

2023-01-08 14:45 UTC, cve-team requested changes
Auto validation errors:

2023-01-08 14:45 UTC, cve-team commented on 2022/0xxx/CVE-2022-0668.json
>  {
Duplicate Refs Detected(same URL)

2023-01-08 14:50 UTC, merged