Add CVE-2021-32821 for GHSL-2020-345
CVEProject/cvelist pull request #8443
Opened 2023-01-03 16:48 UTC by shelbyc

Add CVE-2021-32821 for GHSL-2020-345

2023-01-03 16:50 UTC, merged

2023-09-08 20:46 UTC, Marcono1234 commented
It looks like this by accident added a `.DS_Store` file to the repository. Should this be reverted?

2023-09-11 13:19 UTC, shelbyc commented
@Marcono1234 Thanks for letting me know about the `.DS_Store` file! The `.DS_Store` file should be removed.

2023-09-11 21:18 UTC, Marcono1234 commented
Are you planning on doing this, and do you have a direct connection to some of the project maintainers? Because it looks recent PRs weren't answered, and maybe they don't accept regular PRs anymore.

But on the other hand this repository might become obsolete in a few months anyway (see #8855), so in that case it might not matter if the `.DS_Store` file remains.

2023-09-11 21:36 UTC, shelbyc commented
I'm not sure if the PR will go through, but it changes an extraneous file rather than a CVE record, so we'll see.

2024-06-13 10:27 UTC, davidaucoin7377 commented
> Add CVE-2021-32821 for GHSL-2020-345

2024-06-13 10:29 UTC, davidaucoin7377 requested changes
This needs review before finalizing