Bill Situ <Bill.Situ@oracle.com>
CVEProject/cvelist pull request #881
Opened 2021-02-19 02:53 UTC by bsitu

On branch cna/Oracle/CVE-2020-14729v2
 Changes to be committed:
	modified:   2020/14xxx/CVE-2020-14729.json

2021-02-19 02:55 UTC, cve-team requested changes
Auto validation errors:

2021-02-19 02:55 UTC, cve-team commented on 2020/14xxx/CVE-2020-14729.json
>          "reference_data": [
MISC or CONFIRM, but name != url for reference.

2021-03-15 16:23 UTC, cristina479 commented on 2020/14xxx/CVE-2020-14729.json
>          "reference_data": [
The `name` and `url` fields need to have the same value for `MISC` or `CONFIRM` references.

2021-04-01 17:53 UTC, DieNode approved these changes

2021-04-01 17:55 UTC, DieNode approved these changes

2021-04-01 17:55 UTC, DieNode commented on 2020/14xxx/CVE-2020-14729.json
> +                "name": "Remediation is provided at customer visible site",
```suggestion
                "name": "Remediation is provided at customer visible site",
```
```suggestion
                "name": "Remediation is provided at customer visible site",
```

2021-04-01 17:56 UTC, DieNode approved these changes

2021-05-14 22:06 UTC, Rayyan335 approved these changes

2021-05-14 22:06 UTC, Rayyan335 approved these changes

2021-05-17 16:47 UTC, closed without merging

2021-05-17 16:47 UTC, bsitu commented
This has been resolved.