WPScan January Public CVEs
CVEProject/cvelist pull request #932
Opened 2021-02-28 14:59 UTC by ethicalhack3r

First time doing this, please let me know if there's something we have done incorrectly, or something that we can improve.

This first batch was done manually, but we will aim to automate the next batch.

2021-02-28 15:00 UTC, cve-team commented
ethicalhack3r is not recognized currently as an account participating in the Git Pilot. To ensure timely processing of your pull request, please contact the CVE Team using either the CVE Request web form (https://cveform.mitre.org/) or an email (cve@mitre.org) and confirm your identity.

2021-03-01 16:20 UTC, cve-team requested changes
Auto validation errors:

2021-03-01 16:20 UTC, cve-team commented on 2021/24xxx/CVE-2021-24123.json
>  {
'vendor_name' is a required property

2021-03-01 16:20 UTC, cve-team commented on 2021/24xxx/CVE-2021-24123.json
>  {
'version_value' is a required property

2021-03-01 16:20 UTC, cve-team commented on 2021/24xxx/CVE-2021-24124.json
>  {
'vendor_name' is a required property

2021-03-01 16:20 UTC, cve-team commented on 2021/24xxx/CVE-2021-24124.json
>  {
'version_value' is a required property

2021-03-01 16:20 UTC, cve-team commented on 2021/24xxx/CVE-2021-24125.json
>  {
'vendor_name' is a required property

2021-03-01 16:20 UTC, cve-team commented on 2021/24xxx/CVE-2021-24125.json
>  {
'version_value' is a required property

2021-03-01 16:20 UTC, cve-team commented on 2021/24xxx/CVE-2021-24126.json
>  {
'vendor_name' is a required property

2021-03-01 16:20 UTC, cve-team commented on 2021/24xxx/CVE-2021-24126.json
>  {
'version_value' is a required property

2021-03-01 16:20 UTC, cve-team commented on 2021/24xxx/CVE-2021-24127.json
>  {
'vendor_name' is a required property

2021-03-01 16:20 UTC, cve-team commented on 2021/24xxx/CVE-2021-24127.json
>  {
'version_value' is a required property

2021-03-01 16:20 UTC, cve-team commented on 2021/24xxx/CVE-2021-24128.json
>  {
'vendor_name' is a required property

2021-03-01 16:20 UTC, cve-team commented on 2021/24xxx/CVE-2021-24128.json
>  {
'version_value' is a required property

2021-03-01 16:20 UTC, cve-team commented on 2021/24xxx/CVE-2021-24129.json
>  {
'vendor_name' is a required property

2021-03-01 16:20 UTC, cve-team commented on 2021/24xxx/CVE-2021-24129.json
>  {
'version_value' is a required property

2021-03-01 16:20 UTC, cve-team commented on 2021/24xxx/CVE-2021-24130.json
>  {
'vendor_name' is a required property

2021-03-01 16:20 UTC, cve-team commented on 2021/24xxx/CVE-2021-24130.json
>  {
'version_value' is a required property

2021-03-01 16:20 UTC, cve-team commented on 2021/24xxx/CVE-2021-24131.json
>  {
'vendor_name' is a required property

2021-03-01 16:20 UTC, cve-team commented on 2021/24xxx/CVE-2021-24131.json
>  {
'version_value' is a required property

2021-03-01 16:20 UTC, cve-team commented on 2021/24xxx/CVE-2021-24132.json
>  {
'vendor_name' is a required property

2021-03-01 16:20 UTC, cve-team commented on 2021/24xxx/CVE-2021-24132.json
>  {
'version_value' is a required property

2021-03-01 16:20 UTC, cve-team commented on 2021/24xxx/CVE-2021-24133.json
>  {
'vendor_name' is a required property

2021-03-01 16:20 UTC, cve-team commented on 2021/24xxx/CVE-2021-24133.json
>  {
'version_value' is a required property

2021-03-01 16:20 UTC, cve-team commented on 2021/24xxx/CVE-2021-24134.json
>  {
'vendor_name' is a required property

2021-03-01 16:20 UTC, cve-team commented on 2021/24xxx/CVE-2021-24134.json
>  {
'version_value' is a required property

2021-03-01 16:20 UTC, cve-team commented on 2021/24xxx/CVE-2021-24135.json
>  {
'vendor_name' is a required property

2021-03-01 16:20 UTC, cve-team commented on 2021/24xxx/CVE-2021-24135.json
>  {
'version_value' is a required property

2021-03-01 16:20 UTC, cve-team commented on 2021/24xxx/CVE-2021-24136.json
>  {
'vendor_name' is a required property

2021-03-01 16:20 UTC, cve-team commented on 2021/24xxx/CVE-2021-24136.json
>  {
'version_value' is a required property

2021-03-01 16:20 UTC, cve-team commented on 2021/24xxx/CVE-2021-24137.json
>  {
'vendor_name' is a required property

2021-03-01 16:20 UTC, cve-team commented on 2021/24xxx/CVE-2021-24137.json
>  {
'version_value' is a required property

2021-03-01 16:20 UTC, cve-team commented on 2021/24xxx/CVE-2021-24138.json
>  {
'vendor_name' is a required property

2021-03-01 16:20 UTC, cve-team commented on 2021/24xxx/CVE-2021-24138.json
>  {
'version_value' is a required property

2021-03-01 16:20 UTC, cve-team commented on 2021/24xxx/CVE-2021-24139.json
>  {
'vendor_name' is a required property

2021-03-01 16:20 UTC, cve-team commented on 2021/24xxx/CVE-2021-24139.json
>  {
'version_value' is a required property

2021-03-01 16:20 UTC, cve-team commented on 2021/24xxx/CVE-2021-24140.json
>  {
'vendor_name' is a required property

2021-03-01 16:20 UTC, cve-team commented on 2021/24xxx/CVE-2021-24140.json
>  {
'version_value' is a required property

2021-03-01 16:20 UTC, cve-team commented on 2021/24xxx/CVE-2021-24141.json
>  {
'vendor_name' is a required property

2021-03-01 16:20 UTC, cve-team commented on 2021/24xxx/CVE-2021-24141.json
>  {
'version_value' is a required property

2021-03-01 16:20 UTC, cve-team commented on 2021/24xxx/CVE-2021-24142.json
>  {
'vendor_name' is a required property

2021-03-01 16:20 UTC, cve-team commented on 2021/24xxx/CVE-2021-24142.json
>  {
'version_value' is a required property

2021-03-01 16:20 UTC, cve-team commented on 2021/24xxx/CVE-2021-24143.json
>  {
'vendor_name' is a required property

2021-03-01 16:20 UTC, cve-team commented on 2021/24xxx/CVE-2021-24143.json
>  {
'version_value' is a required property

2021-03-01 16:20 UTC, cve-team commented on 2021/24xxx/CVE-2021-24144.json
>  {
'vendor_name' is a required property

2021-03-01 16:20 UTC, cve-team commented on 2021/24xxx/CVE-2021-24144.json
>  {
'version_value' is a required property

2021-03-01 16:20 UTC, cve-team commented on 2021/24xxx/CVE-2021-24145.json
>  {
'vendor_name' is a required property

2021-03-01 16:20 UTC, cve-team commented on 2021/24xxx/CVE-2021-24145.json
>  {
'version_value' is a required property

2021-03-01 16:20 UTC, cve-team commented on 2021/24xxx/CVE-2021-24146.json
>  {
'vendor_name' is a required property

2021-03-01 16:20 UTC, cve-team commented on 2021/24xxx/CVE-2021-24146.json
>  {
'version_value' is a required property

2021-03-01 16:20 UTC, cve-team commented on 2021/24xxx/CVE-2021-24147.json
>  {
'vendor_name' is a required property

2021-03-01 16:20 UTC, cve-team commented on 2021/24xxx/CVE-2021-24147.json
>  {
'version_value' is a required property

2021-03-01 16:20 UTC, cve-team commented on 2021/24xxx/CVE-2021-24148.json
>  {
'vendor_name' is a required property

2021-03-01 16:20 UTC, cve-team commented on 2021/24xxx/CVE-2021-24148.json
>  {
'version_value' is a required property

2021-03-01 16:20 UTC, cve-team commented on 2021/24xxx/CVE-2021-24149.json
>  {
'vendor_name' is a required property

2021-03-01 16:20 UTC, cve-team commented on 2021/24xxx/CVE-2021-24149.json
>  {
'version_value' is a required property

2021-03-02 09:28 UTC, ethicalhack3r commented
I'll get these fixed next week

2021-03-09 11:02 UTC, ethicalhack3r commented
Adding `Unknown` as `vendor_name` value as each plugin has a different vendor, which we don't record

2021-03-09 11:05 UTC, cve-team requested changes
Auto validation errors:

2021-03-09 11:05 UTC, cve-team commented on 2021/24xxx/CVE-2021-24123.json
>  {
'version_value' is a required property

2021-03-09 11:05 UTC, cve-team commented on 2021/24xxx/CVE-2021-24124.json
>  {
'version_value' is a required property

2021-03-09 11:05 UTC, cve-team commented on 2021/24xxx/CVE-2021-24125.json
>  {
'version_value' is a required property

2021-03-09 11:05 UTC, cve-team commented on 2021/24xxx/CVE-2021-24126.json
>  {
'version_value' is a required property

2021-03-09 11:05 UTC, cve-team commented on 2021/24xxx/CVE-2021-24127.json
>  {
'version_value' is a required property

2021-03-09 11:05 UTC, cve-team commented on 2021/24xxx/CVE-2021-24128.json
>  {
'version_value' is a required property

2021-03-09 11:05 UTC, cve-team commented on 2021/24xxx/CVE-2021-24129.json
>  {
'version_value' is a required property

2021-03-09 11:05 UTC, cve-team commented on 2021/24xxx/CVE-2021-24130.json
>  {
'version_value' is a required property

2021-03-09 11:05 UTC, cve-team commented on 2021/24xxx/CVE-2021-24131.json
>  {
'version_value' is a required property

2021-03-09 11:05 UTC, cve-team commented on 2021/24xxx/CVE-2021-24132.json
>  {
'version_value' is a required property

2021-03-09 11:05 UTC, cve-team commented on 2021/24xxx/CVE-2021-24133.json
>  {
'version_value' is a required property

2021-03-09 11:05 UTC, cve-team commented on 2021/24xxx/CVE-2021-24134.json
>  {
'version_value' is a required property

2021-03-09 11:05 UTC, cve-team commented on 2021/24xxx/CVE-2021-24135.json
>  {
'version_value' is a required property

2021-03-09 11:05 UTC, cve-team commented on 2021/24xxx/CVE-2021-24136.json
>  {
'version_value' is a required property

2021-03-09 11:05 UTC, cve-team commented on 2021/24xxx/CVE-2021-24137.json
>  {
'version_value' is a required property

2021-03-09 11:05 UTC, cve-team commented on 2021/24xxx/CVE-2021-24138.json
>  {
'version_value' is a required property

2021-03-09 11:05 UTC, cve-team commented on 2021/24xxx/CVE-2021-24139.json
>  {
'version_value' is a required property

2021-03-09 11:05 UTC, cve-team commented on 2021/24xxx/CVE-2021-24140.json
>  {
'version_value' is a required property

2021-03-09 11:05 UTC, cve-team commented on 2021/24xxx/CVE-2021-24141.json
>  {
'version_value' is a required property

2021-03-09 11:05 UTC, cve-team commented on 2021/24xxx/CVE-2021-24142.json
>  {
'version_value' is a required property

2021-03-09 11:05 UTC, cve-team commented on 2021/24xxx/CVE-2021-24143.json
>  {
'version_value' is a required property

2021-03-09 11:05 UTC, cve-team commented on 2021/24xxx/CVE-2021-24144.json
>  {
'version_value' is a required property

2021-03-09 11:05 UTC, cve-team commented on 2021/24xxx/CVE-2021-24145.json
>  {
'version_value' is a required property

2021-03-09 11:05 UTC, cve-team commented on 2021/24xxx/CVE-2021-24146.json
>  {
'version_value' is a required property

2021-03-09 11:05 UTC, cve-team commented on 2021/24xxx/CVE-2021-24147.json
>  {
'version_value' is a required property

2021-03-09 11:05 UTC, cve-team commented on 2021/24xxx/CVE-2021-24148.json
>  {
'version_value' is a required property

2021-03-09 11:05 UTC, cve-team commented on 2021/24xxx/CVE-2021-24149.json
>  {
'version_value' is a required property

2021-03-11 08:49 UTC, ethicalhack3r commented
I think this should be ready to merge now?

2021-03-12 15:28 UTC, lsekela commented
The prose descriptions supplied are missing any product/vendor information. A CVE description (8.2.1) MUST provide enough information for a reader to have a reasonable understanding of what products are affected. You can find requirements and an example of prose descriptions at https://cve.mitre.org/cve/list_rules_and_guidance/cve_assignment_information_format.html

2021-03-15 16:52 UTC, cristina479 commented
Please fix the inconsistencies between the versions in the description and the version information in the `version` field for the CVEs. As an example, the description of CVE-2021-24125 indicates that versions less than 1.6.4 (not including 1.6.4) are affected but the version field indicates that version <= 1.6.4 are affected. Thank you.

2021-03-15 17:05 UTC, ethicalhack3r commented
Thank you Christina, I'll review and get that fixed tomorrow.

Please excuse us for the mistakes, this is our first time submitting but plan to automate this process in the future, which should hopefully reduce the mistakes.

2021-03-15 18:17 UTC, cristina479 commented
> Thank you Christina, I'll review and get that fixed tomorrow.
> 
> Please excuse us for the mistakes, this is our first time submitting but plan to automate this process in the future, which should hopefully reduce the mistakes.

No problem. Glad to help.

2021-03-18 13:56 UTC, ethicalhack3r commented
I think this should be OK now?

2021-03-18 15:00 UTC, merged