Publish CVE-2020-7331.json
CVEProject/cvelist pull request #95
Opened 2020-11-12 09:34 UTC by ssarangi1202

SB is live

2020-11-12 09:35 UTC, cve-team requested changes
Auto validation errors:

2020-11-12 09:35 UTC, cve-team commented on 2020/7xxx/CVE-2020-7331.json
>  {
'vendor_name' is a required property

2020-11-16 23:20 UTC, cristina479 commented
@ssarangi1202 Please resolve the conflicts and address the validation errors so that we can publish the changes of CVE-2020-7331.

2020-11-18 10:26 UTC, ssarangi1202 commented
I have made the changes and have updated the CVE. Kindly approve.

2020-11-19 16:58 UTC, cristina479 commented on 2020/7xxx/CVE-2020-7331.json
> +                                            "version_affected": "<=",
If version <= 10.6.1 September 2020 Update are affected then they should also be included in the description

2020-11-20 15:40 UTC, merged